"""行动卡池 —— 全游戏最大的一份内容。

一局只有 38 个行动点（见 ``config.AP_BY_SEMESTER``），属性现实可达区间是 0-25。
所以**每一张卡的总属性点都控制在 4-8**（硬上限 9），代价走 ``resources``
（疲劳 / 经济），不能靠堆数字来表达“这张卡很强”。

每个学期槽的设计含义（本文件按 config 的意图把 16 个学期槽摊成 8 个半学年，
每半个学年占 2 个槽 —— 与 config 里「第 13 学期 = 大四上」「第 16 学期 = 大四下」
的注释一致）::

    1-2   大一上     3-4   大一下     5-6   大二上     7-8   大二下
    9-10  大三上    11-12  大三下    13-14  大四上    15-16  大四下

---------------------------------------------------------------- 覆盖计划
【通用卡】110 张（要求 >=90），全部 ``majors=()``。
  - 8 张 ``safe`` 保底卡区间都是 1-16，任何学期都至少有 8 张可用卡；
  - 其余按上面 8 个半学年铺开，实测每个学期槽的可用通用卡数量：
    42 / 43 / 51 / 48 / 56 / 55 / 57 / 57 / 56 / 53 / 57 / 54 / 49 / 48 / 31 / 28
    （最少的一学期也有 28 张，底线是 6 张）。
  - 两张转专业卡放在 sem 2 / sem 4（各只在该学期可用），
    一张竞赛选型卡放在 sem 3。

【专业专属卡】234 张，每张只属于一个专业（``is_flex=False``），配额：
``cs 32 / biz 32 / mech 30 / civil 30 / sci 30 / hum 28 / ocean 26 / med 26``。
写法是"每个半学年一个块，块内每张卡的区间跨 4-6 个学期"，
所以相邻块的覆盖互相重叠，越靠中间学期可用卡越多。

实测每个 (专业, 学期) 的专属可用卡数量（列 = sem 1..16）::

    cs    2  4  7  8 12 10 13 12 15 12 13 10 11  9  6  5
    mech  3  4  7  8  9  8  9  8 14 11 13 13 12  9  7  7
    civil 3  4  7  8  9  8 11  9 12 11 12 12 12 10  9  9
    sci   3  4  7  8  9  8 12 10 12 11 11 11 11 10 10  8
    biz   2  4  8  8 11  9 11  9 15 13 13 12 13 13  9  9
    ocean 3  4  7  8  9  8 12  9 12 12 11 11  9  9  6  5
    med   3  4  8  8  9  8 12  9 12 11 11 11  9  9  6  5
    hum   4  4  8  8  9  8 12  9 11 11 11 11 10 10  8  7

最小格子是 (cs, sem1) 与 (biz, sem1) 的 2 张，**全部 128 个格子都 >=2**。
学期边界（sem 1 与 sem 15-16）刻意多放了几张，因为卡片区间在这里最容易漏。
``semester_coverage(major_id)`` 可以随时复算这张表。

【竞赛卡】不手写，由 ``contests.STAGE_CARDS`` 在导入时循环生成
（73 个竞赛共 210 阶 → 210 张卡，数量与 STAGE_CARDS 的总阶数严格相等）。
每张卡零属性收益（收益由 ``effects.py`` 按阶梯基数 + 竞赛 strengths 算），
只负责"这个学期你可以去打这一阶"。
"""

from __future__ import annotations

from dataclasses import dataclass

from . import config as C
from . import majors as M
from . import contests as K


# ================================================================ 卡片结构


@dataclass(frozen=True)
class ActionCard:
    """一张行动卡。字段顺序与 ``docs/CONTENT_SPEC.md`` 第 5 节完全一致。"""

    id: str
    name: str                       # <=8 个汉字，卡片标题
    text: str                       # 1-2 句，写清“你具体干了什么”，<=60 字
    rarity: str
    sem_lo: int                     # 最早可用学期
    sem_hi: int                     # 最晚可用学期
    effects: dict[str, int]         # 属性收益（权重）
    resources: dict[str, int]       # {"fatigue": +2, "money": -3}，可空
    flags: tuple[str, ...]          # 触发的 flag，可空
    hobby: tuple[str, int] | None   # (爱好 id, 经验)，可空
    majors: tuple[str, ...]         # () = 通用卡；否则只有这些专业可见
    is_flex: bool                   # True = 相邻专业也能看见
    tags: tuple[str, ...]
    track: str                      # 归属赛道，"" = 通用
    attribute_gate: dict[str, int]  # 前置门槛，可空
    start_affinity: tuple[str, ...] # 只给这些起步线额外露出，() = 所有人
    contest_id: str                 # 竞赛关联（一般 ""）
    contest_tier: str               # 竞赛阶梯（一般 ""）
    note: str                       # 给复盘用的一句旁白，可空


def _c(
    cid: str,
    name: str,
    rarity: str,
    sem_lo: int,
    sem_hi: int,
    text: str,
    effects: dict[str, int],
    *,
    resources: dict[str, int] | None = None,
    flags: tuple[str, ...] = (),
    hobby: tuple[str, int] | None = None,
    majors: tuple[str, ...] = (),
    is_flex: bool = False,
    tags: tuple[str, ...] = (),
    track: str = "",
    gate: dict[str, int] | None = None,
    affinity: tuple[str, ...] = (),
    contest_id: str = "",
    contest_tier: str = "",
    note: str = "",
) -> ActionCard:
    """构造一张行动卡。省掉一堆重复的空字段，内容本身才是重点。"""
    return ActionCard(
        id=cid,
        name=name,
        text=text,
        rarity=rarity,
        sem_lo=sem_lo,
        sem_hi=sem_hi,
        effects=dict(effects),
        resources=dict(resources or {}),
        flags=tuple(flags),
        hobby=hobby,
        majors=tuple(majors),
        is_flex=is_flex,
        tags=tuple(tags),
        track=track,
        attribute_gate=dict(gate or {}),
        start_affinity=tuple(affinity),
        contest_id=contest_id,
        contest_tier=contest_tier,
        note=note,
    )


# ================================================================ 通用卡

GENERAL_CARDS: tuple[ActionCard, ...] = (
    # ---------------------------------------------------------- 大一上（1-2）
    _c("a_military_training", "军训淬火", "common", 1, 2,
       "军训两周晒脱了一层皮，站军姿站到腿抖，但和同排的人混熟了，解散那天有人喊你一起去吃饭。",
       {"body": 3, "network": 2, "mind": 1}, tags=("body", "social"),
       note="晒得最黑的那两周，是大学里最不需要动脑的日子。"),
    _c("a_first_class_meeting", "第一次班会", "common", 1, 2,
       "班会上被推上去做自我介绍，硬着头皮讲了三分钟家乡和爱好，下台后有三个同学主动加了你微信。",
       {"network": 3, "leadership": 1, "mind": 1}, tags=("social", "network"),
       note="后来你才知道，那三分钟决定了别人四年怎么叫你。"),
    _c("a_high_math_project", "高数当项目", "common", 1, 3,
       "把高数作业当成项目来做，每道题都写完整推导，还去蹭了数分习题课，期中排名意外进了班级前十。",
       {"gpa": 4, "mind": 1}, tags=("study", "gpa"),
       note="第一次发现，把一件事做扎实是会上瘾的。"),
    _c("a_cet4_words", "四级单词打卡", "common", 1, 4,
       "从开学第一周起每天背五十个单词，手机打卡到第一百天，真题听力磨到能听懂大意。",
       {"english": 4, "mind": 1}, tags=("english", "study"),
       note="打卡记录没什么用，词汇量有用。"),
    _c("a_club_fair", "百团大战", "common", 1, 2,
       "百团大战那天绕了三圈，最后报了摄影社和辩论队，交掉四十块会费，还抱回一摞传单。",
       {"network": 2, "portfolio": 1, "mind": 1}, hobby=("art", C.HOBBY_XP_PER_ACTION),
       tags=("social", "network", "hobby_art")),
    _c("a_union_interview", "学生会面试", "common", 1, 2,
       "抱着试试看的心态去学生会面试，被连问三个刁钻问题，居然过了初试，成了办公室的干事。",
       {"leadership": 3, "network": 2}, affinity=("cadre",),
       tags=("leadership", "social")),
    _c("a_class_committee", "竞选学委", "common", 1, 2,
       "上台竞选学习委员，讲了自己高中当课代表的经历，票数第二当选，从此开始收作业和催签到。",
       {"leadership": 3, "gpa": 1, "network": 1}, affinity=("cadre",),
       tags=("leadership", "study", "social")),
    _c("a_lab_briefing", "实验室宣讲", "common", 1, 3,
       "去听了院里三个课题组的宣讲，把每位老师的方向和招人要求记在备忘录里，散场后加了一位师兄的微信。",
       {"research": 2, "network": 2, "mind": 1}, tags=("lab", "research", "network"),
       note="那天你第一次知道，本科生的科研是从加微信开始的。"),
    _c("a_major_change_briefing", "转专业宣讲", "common", 1, 3,
       "挤在报告厅听转专业政策宣讲，把绩点要求、名额和考试科目一条条抄进备忘录。",
       {"gpa": 1, "network": 2, "mind": 1}, tags=("study", "network")),
    _c("a_dorm_night_talk", "宿舍夜谈", "common", 1, 8,
       "熄灯后和室友聊到凌晨两点，从高中聊到以后的打算，第二天大家默契地把宿舍卫生排了班。",
       {"mind": 3, "network": 2}, tags=("social", "mind", "rest")),
    _c("a_library_seat", "图书馆占座", "common", 1, 8,
       "每天早上七点半去图书馆排队，抢到四楼靠窗的位置，一坐就是一整天，效率比在宿舍高得多。",
       {"gpa": 3, "mind": 1}, tags=("study", "gpa")),
    _c("a_morning_class", "早八不逃", "common", 1, 4,
       "整整一学期没缺过早八，坐在第三排把板书抄满两本，期末复习时发现笔记比教材好用。",
       {"gpa": 3, "body": 1, "mind": 1}, tags=("study", "gpa", "body")),
    _c("a_english_corner", "英语角开口", "common", 1, 6,
       "硬着头皮去英语角，第一次开口讲了十分钟，被纠正七八个发音，第二次就敢主动搭话了。",
       {"english": 3, "network": 1, "mind": 1}, tags=("english", "social")),
    _c("a_first_volunteer", "校运志愿者", "common", 1, 6,
       "报名做校运会志愿者，在检录处站了一整天，嗓子喊哑了，但拿到了第一张志愿时长证明。",
       {"network": 2, "body": 1, "mind": 1}, hobby=("volunteer", C.HOBBY_XP_PER_ACTION),
       tags=("volunteer", "hobby_volunteer", "social")),
    _c("a_major_interview", "专业认知访谈", "common", 1, 4,
       "约了两位大三学长喝奶茶，问清这个专业到底学什么、后面会忙成什么样，回来整理成一页纸。",
       {"network": 3, "mind": 1}, tags=("network", "social"),
       note="信息差是大学里最便宜也最贵的东西。"),
    _c("a_time_table", "排一张时间表", "common", 1, 6,
       "用表格把每周的课、作业和社团活动排进日历，第一次发现自己每天还能空出两小时。",
       {"gpa": 2, "mind": 2}, tags=("study", "mind")),
    _c("a_canteen_friend", "食堂拼桌", "common", 1, 6,
       "在食堂和陌生人拼桌，从选课聊到考研，后来成了能互相借笔记、代签到的关系。",
       {"network": 3, "mind": 1}, tags=("social", "network")),
    _c("a_first_guitar", "二手吉他", "common", 1, 6,
       "用生活费买了把二手吉他，跟着视频练了两个月，能在宿舍楼下完整弹唱一首歌。",
       {"mind": 2, "portfolio": 2}, hobby=("music", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_music", "mind", "rest")),
    _c("a_photo_walk", "周末扫街", "common", 1, 8,
       "背着相机在老城区走了一下午，拍了两百多张，挑出九张调完色发在社交平台上。",
       {"portfolio": 3, "mind": 2}, hobby=("art", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_art", "portfolio", "rest")),
    _c("a_reading_month", "读完一本书", "common", 1, 8,
       "从图书馆借了本厚厚的通识书，两周看完还写了三千字笔记，第一次觉得写东西没那么难。",
       {"mind": 2, "portfolio": 1, "english": 1}, hobby=("reading", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_reading", "mind", "rest")),
    _c("a_game_night", "开黑到凌晨", "common", 1, 6,
       "和室友连麦打到凌晨三点，第二天早八睡过去两节课，但你们的关系确实是靠这几局处出来的。",
       {"mind": 3, "network": 2}, resources={"fatigue": 3}, hobby=("gaming", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_gaming", "rest", "social")),
    _c("a_binge_series", "追完一部剧", "common", 1, 8,
       "用三个晚上追完二十四集，眼睛熬红了，但在朋友圈写的长评被同学转了好几轮。",
       {"mind": 3, "portfolio": 1}, hobby=("screen", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_screen", "rest", "mind")),
    _c("a_cook_in_dorm", "宿舍煮面", "common", 1, 8,
       "偷偷在宿舍用小锅煮面，加蛋加青菜，分给室友一人一口，从此每周都有人问你今晚煮不煮。",
       {"mind": 2, "body": 1, "network": 1}, hobby=("food", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_food", "rest", "social")),
    _c("a_basketball_wed", "周三打球", "common", 1, 10,
       "每周三下午固定去球场打半场，从被虐到能投进球，认识了一帮球搭子，身体也明显好了。",
       {"body": 3, "network": 2, "mind": 1}, hobby=("sport", C.HOBBY_XP_PER_ACTION),
       tags=("sport", "body", "hobby_sport", "rest")),
    _c("a_teacher_office", "课后堵老师", "common", 1, 8,
       "下课后堵着老师问了三个问题，老师让你下周去办公室，顺手给了你一份往年的卷子。",
       {"gpa": 3, "research": 1, "network": 1}, tags=("study", "gpa", "network")),
    _c("a_note_share", "笔记共享", "common", 1, 8,
       "把一学期的课堂笔记整理成电子版发到班群，有人在下面刷了一排感谢，期末有人请你喝奶茶。",
       {"gpa": 2, "network": 2, "mind": 1}, tags=("study", "gpa", "social")),
    _c("a_phone_curfew", "睡前不刷手机", "common", 1, 14,
       "把手机放在桌上充电，强迫自己十一点半躺下，坚持了三周，早上的脑子终于清醒了。",
       {"mind": 2, "body": 2}, tags=("rest", "mind", "body")),
    _c("a_campus_job", "勤工助学", "common", 1, 6,
       "申请了图书馆的勤工助学岗，每周值班六个小时，一边上架一边把想看的书先翻了一遍。",
       {"network": 2, "mind": 2}, resources={"money": 6},
       tags=("work", "money", "mind")),
    _c("a_museum_visit", "逛博物馆", "common", 1, 14,
       "趁免费开放日逛了市博物馆，在一个展厅里站了四十分钟，回来查了一晚上相关的资料。",
       {"mind": 2, "portfolio": 1, "english": 1}, tags=("mind", "rest", "hobby_art")),
    _c("a_movie_night", "电影之夜", "common", 1, 14,
       "和两个同学在宿舍投屏看老电影，看完争论到半夜，你写的短评被发到了班级公众号上。",
       {"mind": 2, "portfolio": 1}, hobby=("screen", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_screen", "rest", "mind")),
    _c("a_food_explore", "探店一顿", "common", 1, 14,
       "照着攻略去吃了学校后街评分最高的小馆子，人均三十块，回来的路上顺手拍了条短视频。",
       {"mind": 2, "network": 1}, resources={"money": -4}, hobby=("food", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_food", "rest", "social")),
    # ---------------------------------------------------------- 大一下（3-4）
    _c("a_cet4_sprint", "四级冲刺", "common", 3, 5,
       "考前一个月每天一套真题，把听力的错题反复听到能跟读，最后考了五百三十多分。",
       {"english": 3, "exam": 1, "mind": 1}, flags=("cet4",),
       tags=("english", "exam"),
       note="四级这东西，过了就再也没人问你多少分。"),
    _c("a_driving_license", "考驾照", "common", 3, 8,
       "暑假回家报了驾校，科目二挂了两次，第三次压线通过时在车里喊了一声，教练都笑了。",
       {"body": 1, "mind": 2, "network": 1}, tags=("cert", "mind", "body"),
       note="会开车这件事，毕业那年你会感谢现在的自己。"),
    _c("a_dachuang_team", "组队大创", "common", 3, 8,
       "在群里拉了四个人做大创，第一次开会就为选题吵了两小时，最后定了一个谁都没想到的方向。",
       {"research": 2, "network": 2, "portfolio": 1}, flags=("dachuang_started",),
       tags=("project", "research", "network")),
    _c("a_party_application", "手抄申请书", "common", 3, 8,
       "晚自习后手抄了三千八百字入党申请书，第二天一早交到辅导员办公室，手心全是汗。",
       {"leadership": 2, "mind": 1, "network": 1}, flags=("party_applied",),
       tags=("party", "leadership")),
    _c("a_volunteer_teach", "暑期支教", "common", 3, 9,
       "跟着支教队去县中学待了两周，教初二数学，走的时候有学生在黑板上写了“谢谢老师”。",
       {"mind": 3, "leadership": 1, "network": 1}, hobby=("volunteer", C.HOBBY_XP_PER_ACTION),
       tags=("volunteer", "hobby_volunteer", "mind"),
       note="你教给他们的，可能不如他们教给你的多。"),
    _c("a_part_time_shop", "奶茶店兼职", "common", 3, 9,
       "在後街的奶茶店做了两个月兼职，一小时十八块，练出三十秒记住六杯订单的本事。",
       {"network": 2, "mind": 2, "body": 1}, resources={"money": 8, "fatigue": 4},
       tags=("work", "money", "body")),
    _c("a_first_email", "第一封请教信", "common", 3, 10,
       "给保研到顶尖学校的学长写了六百字请教邮件，改四遍才敢发，第二天收到两千字回复。",
       {"network": 3, "mind": 1}, tags=("network", "social"),
       note="大多数人都愿意帮一个认真提问的学弟学妹。"),
    _c("a_senior_dinner", "请学长吃饭", "common", 3, 12,
       "请两位直系学长吃了顿火锅，问清保研加分细则和实习内推的门道，回来画了张时间表。",
       {"network": 3, "mind": 1}, resources={"money": -5},
       tags=("network", "social")),
    _c("a_dorm_conflict", "处理宿舍矛盾", "common", 3, 14,
       "因为作息吵了一架，冷静两天后你主动约对方在操场走了三圈，把话摊开说清楚了。",
       {"mind": 3, "network": 2}, tags=("social", "mind"),
       note="把话说开比忍着有用，虽然更难。"),
    _c("a_band_practice", "组个乐队", "common", 3, 12,
       "和三个网友在活动室排练了两个月，校园歌手大赛上唱了两首，台下有人举着手机录。",
       {"portfolio": 3, "network": 2, "mind": 1}, hobby=("music", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_music", "portfolio", "social")),
    _c("a_blood_donate", "第一次献血", "common", 3, 14,
       "在献血车前犹豫了十分钟才上车，攥着拳头看血袋慢慢变满，下车领到一张献血证和两包饼干。",
       {"mind": 2, "body": 1, "network": 1}, hobby=("volunteer", C.HOBBY_XP_PER_ACTION),
       tags=("volunteer", "hobby_volunteer", "body")),
    _c("a_volunteer_race", "马拉松志愿者", "common", 3, 14,
       "凌晨四点半起床去马拉松补给站，一上午递出去六百多杯水，喊加油喊到失声。",
       {"network": 2, "body": 1, "mind": 2}, hobby=("volunteer", C.HOBBY_XP_PER_ACTION),
       tags=("volunteer", "hobby_volunteer", "body")),
    _c("a_calligraphy", "练字静心", "common", 3, 14,
       "买了字帖每晚写一页，写到第三个月发现自己的课堂笔记都变得好看了，心也静下来。",
       {"mind": 3, "portfolio": 1}, hobby=("art", C.HOBBY_XP_PER_ACTION),
       tags=("hobby_art", "mind", "rest")),
    _c("a_minor_apply", "辅修报名", "common", 5, 9,
       "报了金融学辅修，周末两天全在另一个校区上课，期末同时考八门，累但眼界确实开了。",
       {"gpa": 2, "exam": 1, "network": 1, "mind": 1}, resources={"fatigue": 5},
       tags=("study", "gpa")),
    # ---------------------------------------------------------- 大二上（5-6）
    _c("a_professional_course", "专业课死磕", "common", 5, 10,
       "专业基础课一节没落，课后把教材例题全部重推一遍，期末考了九十一分，是班里第三。",
       {"gpa": 4, "mind": 1}, tags=("study", "gpa"),
       note="基础课学扎实，后面才有资格谈方向。"),
    _c("a_lab_chores", "进组打杂", "common", 5, 11,
       "进实验室从最没技术含量的活干起，配试剂、洗器材、整理数据，干了一个月才摸到正经课题。",
       {"research": 3, "network": 1, "mind": 1}, tags=("lab", "research"),
       note="每个师兄都是从洗瓶子开始的。"),
    _c("a_dachuang_progress", "大创推进", "common", 5, 11,
       "把大创的中期材料补齐，跑了三组对照实验，指导老师批注写满两页，你一条条改到凌晨。",
       {"research": 2, "portfolio": 2, "network": 1}, tags=("project", "research", "portfolio")),
    _c("a_org_minister", "留任部长", "common", 5, 10,
       "在换届大会上讲了五分钟述职，说自己这一年办成了什么，当选副部长，开始带六个新人。",
       {"leadership": 4, "network": 2}, affinity=("cadre",),
       tags=("leadership", "social")),
    _c("a_cet6_first", "六级首考", "common", 5, 10,
       "六级首考前听听力听到耳鸣，考场上阅读做得很顺，作文套用了背熟的三个句型，一次过线。",
       {"english": 3, "mind": 1}, flags=("cet6",), tags=("english", "exam")),
    _c("a_tutor_job", "做家教", "common", 5, 12,
       "经学长介绍给一个初三学生补数学，一小时一百二，讲题讲到自己把初中知识重学了一遍。",
       {"network": 2, "mind": 2}, resources={"money": 9},
       tags=("work", "money", "mind")),
    _c("a_lecture_series", "连听三场讲座", "common", 5, 14,
       "一周听了三场讲座，其中一场讲人工智能伦理，散场后你追着讲者问了两个问题。",
       {"research": 2, "network": 1, "mind": 2}, tags=("research", "mind")),
    _c("a_counseling", "走进心理中心", "common", 5, 16,
       "连着两周睡不好，去了学校心理中心，咨询师听你讲完说“你已经扛了很多”，出来时眼睛是热的。",
       {"mind": 4, "body": 1}, tags=("mind", "rest"),
       note="承认自己撑不住，也是一种能力。"),
    _c("a_cycling_trip", "百公里骑行", "common", 5, 14,
       "国庆骑车去了一百公里外的水库，爬坡时想弃车走人，到山顶看到日落，觉得值了。",
       {"body": 3, "mind": 3}, hobby=("sport", C.HOBBY_XP_PER_ACTION),
       tags=("sport", "body", "mind", "hobby_sport", "rest")),
    _c("a_tea_with_teacher", "请老师喝茶", "common", 5, 15,
       "拿着自己写的一份小报告去办公室找老师聊，老师讲了四十分钟，还把你拉进了课题组的群。",
       {"network": 3, "research": 1, "mind": 1}, tags=("network", "social", "research")),
    # ---------------------------------------------------------- 大二下（7-8）
    _c("a_dachuang_finish", "大创结题", "common", 7, 11,
       "结题答辩前一晚改PPT到三点，第二天讲了十二分钟，评委问了三个问题，最后拿了良好。",
       {"research": 3, "portfolio": 2, "mind": 1}, flags=("dachuang_done",),
       tags=("project", "research", "portfolio")),
    _c("a_cet6_retake", "六级刷分", "common", 7, 12,
       "为了把六级分数刷上去，每天两篇阅读加一篇翻译，第二次考完对答案时手都在抖。",
       {"english": 3, "mind": 2}, tags=("english", "exam")),
    _c("a_ielts_start", "雅思启动", "common", 7, 12,
       "报了个雅思班，每天精听一小时，把剑桥真题从第一套刷到第八套，口语录音自己听了三十遍。",
       {"english": 4, "mind": 1}, resources={"money": -8}, track="abroad",
       tags=("english", "study")),
    _c("a_party_activist", "成为积极分子", "common", 7, 12,
       "被确定为入党积极分子后，每月交一篇思想汇报，上了两次党课，还去了一趟红色教育基地。",
       {"leadership": 2, "exam": 1, "mind": 1}, flags=("party_activist",),
       tags=("party", "exam", "leadership")),
    _c("a_scholarship_apply", "申报学业奖学金", "common", 7, 12,
       "把成绩单、竞赛证书和志愿时长整理成一份申报材料，公示那天在名单里看到自己的名字。",
       {"gpa": 2, "portfolio": 2, "mind": 1}, flags=("scholarship_once",),
       tags=("gpa", "portfolio", "cert"),
       note="第一次因为成绩被公开表扬。"),
    _c("a_self_media", "做自媒体", "common", 5, 12,
       "开了个账号记录大学生活，发了三十条笔记涨了两千粉，还接到过一次品牌寄样。",
       {"portfolio": 3, "network": 1, "mind": 1}, resources={"money": 4},
       tags=("portfolio", "work", "money")),
    _c("a_lit_review", "第一篇综述", "common", 7, 12,
       "把近五年的三十篇英文文献读了一遍，按方法分类做成表格，写出人生第一篇八千字综述。",
       {"research": 3, "english": 1, "portfolio": 1}, tags=("research", "study", "english")),
    _c("a_fitness_cert", "考健身教练证", "common", 7, 14,
       "花三千块报了健身教练培训班，两个月考下国职证书，顺带把自己的体脂降了六个百分点。",
       {"body": 3, "portfolio": 1, "network": 1}, resources={"money": -10},
       flags=("fitness_cert",), tags=("cert", "body", "sport")),
    _c("a_small_intern", "小公司实习", "common", 7, 12,
       "在本地一家做外贸的小公司实习，什么都要干，从整理单据到跟客户开会，第一次懂什么叫先做了再说。",
       {"intern": 3, "network": 1, "mind": 1}, track="job",
       tags=("intern", "work")),
    _c("a_intern_fair", "秋招宣讲会", "common", 7, 14,
       "去听了一场企业宣讲会，散场后挤到前排递了简历，HR 扫了一眼说“大二来得挺早”，你记住了这句话。",
       {"intern": 1, "network": 2, "mind": 2}, track="job",
       tags=("work", "intern", "network")),
    # ---------------------------------------------------------- 大三上（9-10）
    _c("a_major_course_sprint", "专业课冲刺", "common", 9, 13,
       "把三门专业核心课的教材从头到尾啃了一遍，做完整本习题，期末排名冲进专业前百分之十五。",
       {"gpa": 4, "exam": 1, "mind": 1}, tags=("study", "gpa")),
    _c("a_cet6_580", "六级冲580", "common", 9, 14,
       "六级第三刷终于上了五百八，查分那天在图书馆小声叫了出来，截图发给了家里。",
       {"english": 4, "mind": 1}, flags=("cet6_high",), gate={"english": 10},
       tags=("english", "exam"),
       note="数字不重要的，是你为它早起过多少个早晨。"),
    _c("a_first_paper", "论文挂三作", "rare", 9, 14,
       "在师兄的稿子上做了大改，补了两组对照实验，最后挂了第三作者，讨论部分是你写的。",
       {"research": 4, "portfolio": 2, "mind": 1},
       flags=("paper_coauthor",), gate={"research": 8},
       tags=("research", "lab", "portfolio")),
    _c("a_kaoyan_math", "考研数学启动", "common", 9, 14,
       "把数学一的课本从头过了一遍，每天四小时，错题本写到第三本，极限和级数终于不再心慌。",
       {"exam": 4, "gpa": 1, "mind": 1}, track="kaoyan", tags=("exam", "study")),
    _c("a_kaoyan_school", "考研择校", "common", 9, 14,
       "把目标院校近三年的分数线、报录比和参考书全扒了一遍做成表格，最后定下两所。",
       {"exam": 2, "network": 1, "mind": 2}, track="kaoyan", tags=("exam", "network")),
    _c("a_gov_policy", "选调政策调研", "common", 9, 14,
       "把近三年本省选调的公告、专业目录和基层政策整理成对比表，发现专业限制比想象中严。",
       {"exam": 2, "network": 2, "mind": 1}, track="gov", tags=("exam", "network")),
    _c("a_bigtech_intern", "大厂实习", "rare", 9, 14,
       "投了七十多份实习简历面了九家，最后进了一家大厂的日常实习，第一天领到工牌和电脑。",
       {"intern": 5, "network": 2, "mind": 1}, gate={"intern": 8},
       track="job", tags=("intern", "work"),
       note="工牌挂上的那一刻，你突然不慌了。"),
    _c("a_research_group", "正式进组", "common", 9, 14,
       "导师把你加进了课题组周会名单，给你分了一个能写进简历的小课题，还配了一台工位电脑。",
       {"research": 3, "network": 1, "mind": 1}, flags=("lab_member",),
       gate={"research": 8}, track="research", tags=("lab", "research")),
    _c("a_president_race", "竞选主席团", "rare", 9, 12,
       "准备半个月的竞选演讲，在两百人面前讲完自己的三年规划，票数第三，进了主席团。",
       {"leadership": 5, "network": 2, "mind": 1},
       affinity=("cadre",), tags=("leadership", "social"),
       note="站上台那一刻，你已经和刚入学时不一样了。"),
    _c("a_short_trip", "周末短途旅行", "common", 1, 16,
       "和同学坐绿皮车去了隔壁城市，住青旅、爬小山、吃了三顿当地小吃，回来时整个人都松了。",
       {"mind": 3, "body": 2}, resources={"money": -6}, tags=("rest", "mind", "body")),
    # ---------------------------------------------------------- 大三下（11-12）
    _c("a_kaoyan_major_course", "专业课一轮", "common", 11, 16,
       "专业课指定教材刷完第一轮，把十年真题的考点标在目录上，发现重复率比想象中高。",
       {"exam": 5, "mind": 1}, track="kaoyan", tags=("exam", "study")),
    _c("a_camp_apply", "夏令营申请包", "common", 11, 14,
       "花两周把六所学校的夏令营材料准备齐，个人陈述改了七版，推荐信找两位老师签了字。",
       {"portfolio": 3, "network": 2, "mind": 1}, gate={"gpa": 14},
       track="baoyan", tags=("portfolio", "study")),
    _c("a_camp_mock", "面试模拟", "common", 11, 14,
       "和同学互相模拟夏令营面试，被问“你的科研亮点是什么“时卡了壳，回去把答案重写了五遍。",
       {"mind": 2, "portfolio": 2, "english": 1}, track="baoyan",
       tags=("portfolio", "mind")),
    _c("a_paper_submit", "论文投稿", "rare", 11, 16,
       "把做了大半年的结果整理成稿，按期刊格式改了三轮，点下 submit 的那一刻心跳很快。",
       {"research": 4, "portfolio": 2, "mind": 1},
       flags=("paper_submitted",), gate={"research": 12}, track="research",
       tags=("research", "portfolio"),
       note="投出去的那一刻，它就不再只属于你了。"),
    _c("a_taoci_email", "写套磁信", "common", 11, 16,
       "给三位海外教授发了套磁信，两封石沉大海，第三位回了邮件说可以聊聊，你把那封邮件读了三遍。",
       {"research": 2, "network": 2, "english": 1}, track="abroad",
       tags=("network", "research", "english")),
    _c("a_ielts_first", "雅思首考", "common", 9, 15,
       "首考口语遇到一个语速极快的考官，第二部分讲跑题了，出分六分，回家立刻报了下一场。",
       {"english": 3, "mind": 2}, track="abroad", tags=("english", "mind")),
    _c("a_party_full", "入党转正", "rare", 11, 16,
       "支部大会通过你的转正申请，你站在党旗前念完入党誓词，辅导员重重拍了拍你的肩膀。",
       {"leadership": 3, "exam": 2, "mind": 1},
       flags=("party_member",), gate={"leadership": 12}, track="gov",
       tags=("party", "leadership"),
       note="从申请书到这一天，你写了三年。"),
    _c("a_summer_return", "争取实习转正", "rare", 11, 14,
       "暑期实习最后两周主动找主管要了一个完整项目，交付后拿到转正意向，HR 让你等秋招正式批。",
       {"intern": 4, "network": 2, "mind": 1},
       flags=("intern_return_offer",), gate={"intern": 10}, track="job",
       tags=("intern", "work")),
    _c("a_conference", "去听顶会", "common", 11, 16,
       "蹭了在本市举办的学术会议，站在海报前跟两个博士生聊了半小时，回来把研究方向调了个角度。",
       {"research": 3, "english": 1, "network": 1}, gate={"english": 12},
       track="research", tags=("research", "english", "network")),
    _c("a_final_sprint", "期末冲刺", "common", 1, 16,
       "考试周在自习室连坐十一天，把六门课的重点整理成一份五十六页的复习资料，还在班群里共享了。",
       {"gpa": 4}, resources={"fatigue": 6}, tags=("study", "gpa", "exam"),
       note="每学期最后两周，图书馆的灯比谁都亮。"),
    _c("a_gym_card", "办张健身卡", "common", 1, 14,
       "在学校旁边的健身房办了年卡，从只能推空杆到能推起六十公斤，镜子里的人开始有轮廓了。",
       {"body": 4, "mind": 1}, resources={"money": -6},
       tags=("sport", "body", "rest")),
    # ---------------------------------------------------------- 大四上（13-14）
    _c("a_tuimian_submit", "九推投递", "rare", 13, 15,
       "推免系统开放那天守在电脑前，零点一到就填了三个志愿，凌晨收到第一个复试通知时手都在抖。",
       {"portfolio": 3, "mind": 3}, flags=("tuimian_submitted",),
       gate={"gpa": 15}, track="baoyan", tags=("portfolio", "mind"),
       note="前六个学期所有的课，都是为了这一晚。"),
    _c("a_kaoyan_politics", "政治冲刺", "common", 13, 16,
       "从九月起每天早上一小时背政治，肖四肖八选择题刷了三遍，大题背到能默写框架。",
       {"exam": 4, "mind": 1}, track="kaoyan", tags=("exam", "study")),
    _c("a_autumn_apply", "秋招海投", "rare", 13, 16,
       "一个月投了一百二十七份简历，做了十几套笔试，面试从紧张到麻木，最后手里攥着两个 offer。",
       {"intern": 4, "mind": 2, "network": 1},
       flags=("qiuzhao_offer",), gate={"intern": 8}, track="job",
       tags=("work", "intern"),
       note="面试到第十家的时候，你终于不结巴了。"),
    _c("a_xuandiao_apply", "定向选调报名", "common", 13, 16,
       "对照各省定向选调的公告筛了一遍，发现党员和学生干部两条都卡，赶紧补齐材料报了名。",
       {"exam": 3, "leadership": 2, "mind": 1}, gate={"leadership": 10},
       track="gov", tags=("exam", "party", "leadership")),
    _c("a_sop_final", "文书定稿", "common", 11, 16,
       "个人陈述改到第十一版，找在美国读博的学姐逐句抠，最后把开头换成了大三做项目时的一个细节。",
       {"english": 3, "portfolio": 2, "mind": 1}, gate={"english": 14},
       track="abroad", tags=("english", "portfolio")),
    _c("a_thesis_proposal", "毕设开题", "common", 13, 16,
       "开题报告改了四稿，导师把题目范围砍掉一半，答辩时被问“你的创新点在哪”，答得磕磕巴巴。",
       {"research": 3, "mind": 1}, flags=("thesis_started",),
       tags=("research", "study")),
    _c("a_offer_compare", "比 offer", "common", 13, 16,
       "把手里几个 offer 的薪资、城市、加班强度列成表格，问了一圈学长，最后一栏写的是“我想做什么”。",
       {"mind": 3, "intern": 1, "network": 1}, track="job",
       tags=("work", "mind")),
    # ---------------------------------------------------------- 大四下（15-16）
    _c("a_kaoyan_retest", "复试与调剂", "common", 15, 16,
       "初试过线后准备了英文自我介绍和专业课问答，同时填了三个调剂志愿，有惊无险进了复试名单。",
       {"exam": 3, "english": 1, "mind": 2}, gate={"exam": 10},
       track="kaoyan", tags=("exam", "english"),
       note="复试考的不只是知识，还有你说话的样子。"),
    _c("a_spring_apply", "春招补录", "common", 15, 16,
       "秋招没落定的岗位春招又开了一批，你把简历里的项目换成毕设内容，面了三家，拿到一个补录 offer。",
       {"intern": 3, "mind": 2}, track="job", tags=("work", "intern")),
    _c("a_provincial_exam", "省考联考", "common", 15, 16,
       "省考那天早上六点起床，行测最后十五分钟涂完一百二十道题，申论大作文写到手酸。",
       {"exam": 4, "mind": 2}, track="gov", tags=("exam",),
       note="考场外面全是和你一样的人。"),
    _c("a_thesis_finish", "毕设冲刺", "rare", 15, 16,
       "在实验室熬了两个月，仿真跑了三百多次，论文写了四万字，查重率百分之六，答辩拿了优秀。",
       {"research": 4, "portfolio": 2, "mind": 1},
       flags=("thesis_done",), tags=("research", "portfolio"),
       note="四万字的最后，你写了一句“感谢没有放弃的自己”。"),
    _c("a_farewell_dinner", "散伙饭", "rare", 15, 16,
       "散伙饭上大家轮流讲这四年最难忘的事，说到一半有人哭了，最后所有人抱在一起拍了张糊掉的照片。",
       {"mind": 4, "network": 2}, tags=("social", "mind"),
       note="那天的照片很糊，但每个人都笑得很开。"),
    _c("a_graduation_photo", "拍毕业照", "common", 15, 16,
       "穿着租来的学士服在图书馆台阶上排了三排，扔帽子的瞬间被拍了下来，后来成了你的头像。",
       {"mind": 3, "network": 2}, tags=("social", "mind")),
    # ---------------------------------------------------------- 保底休息卡（1-16 全程）
    _c("a_safe_run", "夜跑五公里", "safe", 1, 16,
       "换上跑鞋绕着操场跑了五公里，跑到第三公里时脑子里的杂事全被甩掉了，回宿舍冲个澡睡得很沉。",
       {"body": 3, "mind": 1}, hobby=("sport", C.HOBBY_XP_PER_ACTION),
       tags=("sport", "body", "rest", "hobby_sport"),
       note="跑完那五公里，世界安静了很多。"),
    _c("a_safe_sleep", "早点睡觉", "safe", 1, 16,
       "推掉所有安排，十点半上床，把窗帘拉严，一觉睡到自然醒，第二天像换了个人。",
       {"mind": 2, "body": 2}, resources={"fatigue": -4}, tags=("rest", "mind", "body"),
       note="很多问题，睡一觉真的会好一点。"),
    _c("a_safe_walk", "校园散步", "safe", 1, 16,
       "一个人绕着校园走了两圈，从图书馆走到湖边，看了一会儿灯影，什么也没想。",
       {"mind": 3, "body": 1}, resources={"fatigue": -3}, tags=("rest", "mind", "body")),
    _c("a_safe_badminton", "打羽毛球", "safe", 1, 16,
       "约人在体育馆打了两小时羽毛球，出一身汗，笑到肚子疼，回宿舍路上还在复盘那个扣杀。",
       {"body": 3, "network": 1}, tags=("sport", "body", "rest", "network")),
    _c("a_safe_podcast", "听播客放松", "safe", 1, 16,
       "戴着耳机听了一晚上播客，从科技聊到历史，顺手把有意思的两期记进了备忘录。",
       {"mind": 2, "english": 1, "portfolio": 1}, hobby=("reading", C.HOBBY_XP_PER_ACTION),
       tags=("rest", "mind", "hobby_reading")),
    _c("a_safe_cook", "煮碗热汤面", "safe", 1, 16,
       "认真煮了碗面，煎了蛋、烫了青菜，端到桌上慢慢吃完，觉得日子还是自己的。",
       {"mind": 2, "body": 1, "network": 1}, hobby=("food", C.HOBBY_XP_PER_ACTION),
       tags=("rest", "hobby_food", "mind")),
    _c("a_safe_music", "听歌放空", "safe", 1, 16,
       "关了消息提醒，躺着把一张专辑从头听到尾，什么都不干，半小时后心里松了一大块。",
       {"mind": 3, "body": 1}, hobby=("music", C.HOBBY_XP_PER_ACTION),
       tags=("rest", "mind", "hobby_music")),
    _c("a_safe_stretch", "拉伸放松", "safe", 1, 16,
       "跟着视频做了四十分钟拉伸，肩颈的酸痛松开了，睡前又泡了脚，那晚睡得出奇地好。",
       {"body": 2, "mind": 2}, tags=("rest", "sport", "body"),
       note="身体先放松，脑子才肯休息。"),
    # ---------------------------------------------------------- 关键抉择
    _c("a_change_major_1", "转专业申请", "rare", 2, 2,
       "在截止前一晚把转专业申请表填完，附上一份自己写的学习计划，交表时手心全是汗。",
       {"gpa": 1, "mind": 2, "network": 1},
       flags=("changed_major_pending",), tags=("study", "mind"),
       note="你终于承认，自己不喜欢现在这个专业。"),
    _c("a_change_major_2", "再试一次转专业", "rare", 4, 4,
       "第二次递交转专业申请，这次把目标专业的先修课成绩和读书笔记一起附上，态度比上次更硬。",
       {"gpa": 1, "mind": 2, "portfolio": 1},
       flags=("changed_major_pending",), tags=("study", "mind", "portfolio"),
       note="第二次敲门，你比第一次更清楚自己要什么。"),
    _c("a_pick_contest_main", "竞赛选型", "rare", 3, 3,
       "把院里能打的比赛列成一张表，对照自己的强项和时间，圈定一项作为主攻，其余只当练手。",
       {"portfolio": 1, "mind": 2, "network": 1},
       flags=("contest_main_picked",), affinity=("ace",),
       tags=("contest", "mind"),
       note="同时打五个比赛的人，通常一个奖也拿不到。"),

    # ---------------------------------------------------------------
    # 通用「应试与考证」线（补充 exam 供给）
    #
    # 为什么需要这一组：技能树里的考研线与考公线都吃 exam，但原始卡池里
    # exam 只有 115 点、且大多集中在 sem 9-16，跑道太短，导致考研/考公
    # 两条路几乎打不出来（模拟里解锁率为 0）。这里补一条从大一到大三下
    # 都能走的通用应试线，让"应试能力"成为一条真正可以提前积累的线，
    # 而不是大四才开始的事情。
    # ---------------------------------------------------------------
    _c("a_cert_computer_level2", "报考计算机二级", "common", 2, 8,
       "报了个全国计算机等级考试，把办公软件和基础操作过一遍，顺手拿个能写进简历的证。",
       {"exam": 3, "gpa": 1},
       tags=("cert", "exam", "study"),
       note="最没含金量、也最容易拿到的证之一，但它确实能填空。"),
    _c("a_cert_putonghua", "普通话等级", "common", 2, 8,
       "练了两个月绕口令和朗读，考出二级甲等，为以后可能走的教育或体制方向留条路。",
       {"exam": 2, "english": 1, "mind": 1},
       tags=("cert", "exam", "mind"),
       note="报名费五十块，但普通话是很多资格证的入场券。"),
    _c("a_cert_teacher_qual", "教资笔试", "rare", 4, 11,
       "买了全套教材，跟着网课把综合素质和教育知识过了一遍，笔试卷子刷到第二遍。",
       {"exam": 4, "gpa": 1, "mind": 1},
       gate={"gpa": 6},
       tags=("cert", "exam", "study"),
       note="不一定要当老师，但多一张证就多一条退路。"),
    _c("a_exam_mock_papers", "刷整套模拟卷", "common", 3, 14,
       "按真实考试时间做了三套完整模拟，掐表、涂卡、对答案，把错题按类型整理成册。",
       {"exam": 4, "mind": 1},
       tags=("exam", "study"),
       note="模拟卷的意义不在分数，在于让你知道自己哪一块根本没学会。"),
    _c("a_exam_timing_drill", "练答题节奏", "common", 5, 16,
       "把失去的分一道一道找回来：哪类题该跳过、哪道题该先做、涂卡要留几分钟。",
       {"exam": 3, "mind": 2},
       tags=("exam", "mind"),
       note="考场上丢掉的分，一半不是不会，是没时间。"),
    _c("a_cert_securities", "考证券从业资格", "common", 5, 12,
       "双科都报了，金融市场基础知识和法律法规背了两轮，考前一周每天做三套题。",
       {"exam": 3, "intern": 1},
       tags=("cert", "exam", "work"),
       note="金融类实习的敲门砖，考试本身不难，难的是你愿不愿意花这个时间。"),
    _c("a_exam_current_affairs", "每天刷时政", "common", 4, 16,
       "每天早上花二十分钟看新闻和评论，把这些年发生的事按主题整理进一个本子。",
       {"exam": 3, "leadership": 1},
       tags=("exam", "party"),
       note="申论和面试都用得上，而且是唯一一门越早开始越省力的科目。"),
    _c("a_exam_reading_speed", "练阅读与材料概括", "common", 4, 15,
       "每天限时读三篇长材料，读完用一百字概括，逼自己把抓重点变成肌肉记忆。",
       {"exam": 3, "english": 1, "mind": 1},
       tags=("exam", "study"),
       note="行测和申论共用的核心能力，就是快速看懂一篇长材料。"),
    _c("a_study_major_exam", "啃专业课真题", "rare", 6, 16,
       "把目标院校近十年的专业课真题打印出来，按章节标注考点频率，重画出整门课的骨架。",
       {"exam": 4, "gpa": 2, "research": 1},
       gate={"gpa": 10},
       tags=("exam", "study", "gpa"),
       note="专业课真题会告诉你：哪些章节老师从来没出过题。"),
    _c("a_exam_mind_control", "练考前心态", "common", 6, 16,
       "把模拟考当成真考，练出一套固定的开考前流程：深呼吸、检查文具、先扫一遍全卷。",
       {"exam": 2, "mind": 3},
       tags=("exam", "mind", "rest"),
       note="紧张不是问题，问题是你有没有为紧张准备过流程。"),

    # ---------------------------------------------------------------
    # 通用「组织与影响力」线（补充 leadership 供给）
    #
    # 原始卡池里 leadership 只有 37 点，是十个属性里最贫瘠的一条；
    # 而考公选调线同时吃 exam 和 leadership，所以那条路几乎打不出来。
    # 这里按"不一定要当主席也能积累影响力"的思路补一组：把事办成、
    # 带小团队、做志愿组织、写材料 —— 这些都是真实的组织能力来源。
    # ---------------------------------------------------------------
    _c("a_lead_team_project", "带小组做课程项目", "common", 2, 12,
       "主动认领了小组的分工和进度表，把四个人的活儿拆清楚，最后交出一份像样的报告。",
       {"leadership": 3, "gpa": 1, "network": 1},
       tags=("leadership", "social", "study"),
       note="愿意做那个排进度表的人，比愿意做演示的人少得多。"),
    _c("a_lead_organize_event", "办一次活动", "rare", 3, 12,
       "从场地申请、物资采购到来回借设备，一件件跑下来，活动当天来了六十多人。",
       {"leadership": 4, "network": 2, "body": 1},
       resources={"fatigue": 3},
       tags=("leadership", "social"),
       note="办过一次活动，你就知道「流程」这两个字有多重。"),
    _c("a_lead_class_committee", "当班委", "common", 1, 8,
       "竞选上了学习委员，每周收作业、传达通知、帮同学问老师，事情琐碎但大家都记得你。",
       {"leadership": 3, "network": 2, "mind": 1},
       tags=("leadership", "social"),
       note="班委不是权力，是一堆没人愿意接的碎事。"),
    _c("a_lead_volunteer_organizer", "志愿排班", "common", 4, 14,
       "从报名当志愿者变成排班的那个人，协调了三十多个人的时间和线路。",
       {"leadership": 3, "network": 1, "mind": 2},
       tags=("leadership", "volunteer", "social"),
       note="志愿者容易当，把志愿者管好很难。"),
    _c("a_lead_write_materials", "写材料", "common", 4, 16,
       "接下了总结报告和申报书的活，写了十几稿，学会了怎么把做的事写成能被认可的样子。",
       {"leadership": 3, "exam": 1, "portfolio": 1},
       tags=("leadership", "study", "portfolio"),
       note="同样的成绩，会不会写材料能差出一个奖。"),
    _c("a_lead_mediate_conflict", "处理一次矛盾", "rare", 5, 16,
       "宿舍或者小组里闹了矛盾，你分别找两边聊，最后把事按下去，也让两边都还过得去。",
       {"leadership": 2, "mind": 3, "network": 2},
       tags=("leadership", "mind", "social"),
       note="能处理矛盾的人，会被记住很久。"),
    _c("a_lead_speech_practice", "练公开发言", "common", 3, 16,
       "每次班会都主动说两分钟，回家对着镜子录视频改，把上台的手抖压下去了。",
       {"leadership": 3, "mind": 2, "english": 1},
       tags=("leadership", "mind"),
       note="面试和答辩都是同一件事：你能不能在人前把话说清楚。"),
)


# ================================================================ 专业专属卡

# ---------------------------------------------------------------- 计算机类（32）

CS_CARDS: tuple[ActionCard, ...] = (
    _c("a_cs_first_program", "第一个程序", "common", 1, 4,
       "照着教程敲出人生第一个能跑的程序，一个晚上改了十几次才不报错，跑通那刻在宿舍喊了一声。",
       {"portfolio": 2, "gpa": 1, "mind": 2}, majors=("cs",),
       tags=("study", "portfolio")),
    _c("a_cs_c_language", "啃C语言", "common", 1, 4,
       "把 C 语言教材从头到尾敲了一遍，指针那章看了三遍才懂，课后题做了两百多道。",
       {"gpa": 3, "research": 1}, majors=("cs",), tags=("study", "gpa")),
    _c("a_cs_linux_try", "装个Linux", "common", 2, 5,
       "在旧笔记本上装了双系统，把驱动折腾到凌晨两点，第一次用命令行编译出自己的程序。",
       {"research": 2, "portfolio": 1, "mind": 2}, majors=("cs",),
       tags=("lab", "study")),
    _c("a_cs_oj_daily", "每天一道题", "common", 2, 5,
       "在刷题网站上从最简单的一百题开始，每天一道坚持三个月，看到红色报错不再心慌。",
       {"gpa": 2, "portfolio": 1, "mind": 2}, majors=("cs",),
       tags=("study", "mind")),
    _c("a_cs_git_first", "学Git", "common", 3, 6,
       "把课程项目传到代码托管平台上，第一次用分支和合并，冲突改了一小时才推上去。",
       {"portfolio": 2, "research": 1}, majors=("cs",), tags=("project", "study")),
    _c("a_cs_data_structure", "数据结构死磕", "common", 3, 6,
       "数据结构每章的代码都手写实现了一遍，红黑树那节画满三页纸，期末考了班里第二。",
       {"gpa": 4, "portfolio": 1}, majors=("cs",), tags=("study", "gpa")),
    _c("a_cs_web_page", "第一个网页", "common", 3, 6,
       "用两周做了个静态网页交课程作业，加了轮播和响应式，室友说比学院官网好看。",
       {"portfolio": 3, "mind": 1}, majors=("cs",), tags=("project", "portfolio")),
    _c("a_cs_python_tool", "写个脚本", "common", 4, 7,
       "写了段脚本帮实验室批量处理表格，师兄原本要干一下午的活，跑十分钟就完了。",
       {"research": 2, "portfolio": 2, "network": 1}, majors=("cs",),
       tags=("project", "research")),
    _c("a_cs_os_course", "操作系统三大件", "common", 5, 8,
       "把进程调度和内存管理啃了两遍，实验课自己写了份简化版内核，调了一周才跑起来。",
       {"gpa": 3, "research": 2}, majors=("cs",), tags=("study", "gpa", "research")),
    _c("a_cs_db_project", "数据库大作业", "common", 5, 8,
       "给图书管理系统设计了十几张表，写了触发器和存储过程，答辩时被问索引为什么这么建。",
       {"gpa": 3, "portfolio": 1}, majors=("cs",), tags=("study", "project")),
    _c("a_cs_network_sniff", "计网抓包", "common", 5, 8,
       "用抓包工具把宿舍网络的流量看了一遍，搞明白三次握手长什么样，报告写了二十页。",
       {"research": 3, "gpa": 1}, majors=("cs",), tags=("study", "research")),
    _c("a_cs_algo_book", "啃算法书", "common", 5, 9,
       "跟着经典算法书把动态规划和图论过了一遍，每道例题都自己写一遍再对照题解。",
       {"portfolio": 2, "gpa": 2, "mind": 1}, majors=("cs",),
       tags=("study", "portfolio")),
    _c("a_cs_lanqiao_train", "蓝桥杯备赛", "common", 5, 9,
       "为蓝桥杯刷了三百道真题，把填空题的手算技巧总结成一页纸，赛前一周每天一套模拟。",
       {"portfolio": 3, "mind": 1}, majors=("cs",),
       tags=("contest", "study", "portfolio")),
    _c("a_cs_acm_team", "组队打ACM", "common", 5, 9,
       "和两个同学组了队，每周三晚上在机房合练一场五小时，从爆零到能稳定做出四道题。",
       {"portfolio": 3, "network": 2}, majors=("cs",),
       tags=("contest", "portfolio", "network")),
    _c("a_cs_direction_pick", "定技术方向", "common", 7, 10,
       "把后端、前端、客户端和算法四条路各查了一周，约三位学长聊过之后决定主攻后端。",
       {"mind": 2, "network": 2, "portfolio": 1}, majors=("cs",),
       tags=("mind", "network", "portfolio")),
    _c("a_cs_backend_learn", "后端入门", "common", 7, 11,
       "照着文档搭了一套增删改查的服务，加了登录和分页，部署到服务器时踩了十几个坑。",
       {"portfolio": 3, "intern": 1, "research": 1}, majors=("cs",),
       tags=("project", "portfolio")),
    _c("a_cs_frontend_vue", "学前端框架", "common", 7, 11,
       "花一个月学完前端框架，把课程项目重写成组件化版本，首屏加载快了一半。",
       {"portfolio": 3, "intern": 1}, majors=("cs",), tags=("project", "portfolio")),
    _c("a_cs_android_app", "写个安卓应用", "common", 7, 11,
       "做了个记录课表的小应用，装在自己手机上用了半年，发到论坛还被下载了三百多次。",
       {"portfolio": 3, "intern": 1, "mind": 1}, majors=("cs",),
       tags=("project", "portfolio")),
    _c("a_cs_ml_framework", "跑通深度学习", "common", 7, 12,
       "在实验室服务器上配好深度学习环境，把经典网络在公开数据集上复现到接近论文精度。",
       {"research": 3, "portfolio": 1, "gpa": 1}, majors=("cs",),
       tags=("research", "lab", "project")),
    _c("a_cs_paper_repro", "论文复现", "common", 9, 13,
       "挑了篇顶会论文逐行复现，作者没写的两个超参数试了一周才对上，最后写了份复现报告。",
       {"research": 4, "portfolio": 1}, majors=("cs",), tags=("research", "lab")),
    _c("a_cs_open_source", "给开源提PR", "common", 9, 13,
       "给一个常用的开源库修了个小 bug 并提了合并请求，被维护者夸了一句，那晚高兴得睡不着。",
       {"portfolio": 3, "research": 2, "network": 1}, majors=("cs",),
       tags=("project", "portfolio", "research")),
    _c("a_cs_server_ops", "云服务器运维", "common", 7, 12,
       "买了台云服务器，把域名、证书和定时备份都配齐，半夜被报警短信叫起来重启过一次服务。",
       {"research": 2, "portfolio": 2, "mind": 1}, majors=("cs",),
       tags=("lab", "project")),
    _c("a_cs_ruankao", "考软考中级", "common", 9, 14,
       "报了软考中级软件设计师，十年真题刷了两遍，下午的设计题画满一整本答题纸。",
       {"portfolio": 2, "gpa": 1, "exam": 1}, majors=("cs",),
       flags=("ruankao_mid",), tags=("cert", "exam")),
    _c("a_cs_resume_project", "简历项目包装", "common", 9, 14,
       "把三个课程项目重写成一个能讲清楚的项目，补上量化指标和技术难点，简历改到第五版。",
       {"intern": 2, "portfolio": 2, "mind": 1}, majors=("cs",),
       tags=("work", "portfolio")),
    _c("a_cs_written_exam", "大厂笔试", "common", 9, 14,
       "连着做了七家大厂的笔试，把每家的题型记下来，第三次之后基本能稳定过线。",
       {"intern": 3, "portfolio": 1, "mind": 1}, majors=("cs",),
       tags=("work", "intern", "exam")),
    _c("a_cs_interview_basics", "啃八股", "common", 9, 14,
       "把操作系统、网络和数据库的常见面试题整理成两万字笔记，背到能用自己的话讲出来。",
       {"intern": 3, "gpa": 1, "mind": 1}, majors=("cs",),
       tags=("work", "study")),
    _c("a_cs_mock_interview", "模拟技术面", "common", 11, 15,
       "和同学互相模拟技术面试，被追问项目细节到答不上来，回去把每个技术选型都补了理由。",
       {"intern": 2, "mind": 3}, majors=("cs",), tags=("work", "mind")),
    _c("a_cs_intern_apply", "投暑期实习", "common", 11, 16,
       "前后投了四十多家，面到第五家时终于拿到暑期实习 offer，当天把消息发给了家里。",
       {"intern": 4, "network": 1, "mind": 1}, majors=("cs",),
       tags=("intern", "work")),
    _c("a_cs_interview_season", "秋招面试", "common", 13, 16,
       "一天面三家，从自我介绍到反问环节都练成了肌肉记忆，最后手里拿到两个 offer。",
       {"intern": 3, "mind": 2, "network": 1}, majors=("cs",),
       tags=("work", "intern")),
    _c("a_cs_offer_choice", "选offer", "common", 13, 16,
       "把两个 offer 的薪资、业务和成长空间列成表，问了一圈师兄，选了钱少但方向更喜欢的那个。",
       {"mind": 3, "intern": 1}, majors=("cs",), tags=("work", "mind")),
    _c("a_cs_graduation_system", "毕设做系统", "common", 13, 16,
       "毕设做了一个完整系统，前端后端加部署全自己写，答辩时老师问的全是实现细节。",
       {"research": 3, "portfolio": 2}, majors=("cs",),
       tags=("research", "project", "portfolio")),
    _c("a_cs_onboard_prep", "入职准备", "common", 15, 16,
       "入职前把租房、体检和银行卡一件件办完，还提前把公司要用的技术栈过了一遍。",
       {"intern": 2, "mind": 2, "body": 1}, majors=("cs",),
       tags=("work", "mind")),
)


# ---------------------------------------------------------------- 经管类（32）

BIZ_CARDS: tuple[ActionCard, ...] = (
    _c("a_biz_first_case", "第一个商业案例", "common", 1, 4,
       "课上第一次做商业案例，把一家奶茶店的选址逻辑拆成四页纸，被老师当范例讲了一遍。",
       {"gpa": 2, "portfolio": 2, "mind": 1}, majors=("biz",),
       tags=("study", "portfolio")),
    _c("a_biz_accounting_basic", "会计入门", "common", 1, 4,
       "把会计学原理的借贷关系抄到能默写，课后找了家上市公司的年报硬着头皮翻了一遍。",
       {"gpa": 3, "exam": 1}, majors=("biz",), tags=("study", "gpa")),
    _c("a_biz_econ_read", "读透经济学", "common", 2, 5,
       "把经济学教材通读一遍，试着用供需曲线解释校门口的外卖价格，写了篇两千字笔记。",
       {"gpa": 3, "mind": 1}, majors=("biz",), tags=("study", "gpa")),
    _c("a_biz_biz_news", "每天财经新闻", "common", 2, 5,
       "每天早上花二十分钟读财经新闻，看不懂的名词就查，三个月后能看懂宏观数据发布。",
       {"exam": 2, "mind": 2, "english": 1}, majors=("biz",),
       tags=("study", "mind")),
    _c("a_biz_market_survey", "做市场调查", "common", 3, 6,
       "为课程作业在食堂门口发了二百份问卷，回收一百七十六份，第一次用统计软件跑描述分析。",
       {"research": 2, "portfolio": 2, "network": 1}, majors=("biz",),
       tags=("research", "project")),
    _c("a_biz_excel_skill", "练Excel", "common", 3, 6,
       "把数据透视表和常用函数练熟，帮社团做的活动统计表被夸专业，从此各种表都来找你。",
       {"portfolio": 2, "network": 2, "mind": 1}, majors=("biz",),
       tags=("work", "portfolio")),
    _c("a_biz_plan_first", "写商业计划书", "common", 3, 7,
       "组队写了份商业计划书，财务预测算了三遍才自洽，路演时还是被评委问住了两个问题。",
       {"portfolio": 3, "network": 1, "mind": 1}, majors=("biz",),
       tags=("project", "portfolio")),
    _c("a_biz_ppt_skill", "把PPT做好", "common", 3, 7,
       "花两个晚上重做课程汇报的 PPT，把每页的字砍掉一半，讲完之后有同学来问模板。",
       {"portfolio": 2, "network": 1, "mind": 2}, majors=("biz",),
       tags=("portfolio", "mind")),
    _c("a_biz_primary_accounting", "考初级会计", "common", 5, 9,
       "报名初级会计职称，两门课各刷十套卷子，经济法背到考前最后一晚，一次通过。",
       {"exam": 3, "gpa": 1}, majors=("biz",), flags=("primary_accounting",),
       tags=("cert", "exam")),
    _c("a_biz_securities_cert", "证券从业资格", "common", 5, 9,
       "报了证券从业资格考试，把金融市场基础知识完整过了一遍，两科都考了七十多分。",
       {"exam": 2, "intern": 1, "mind": 1}, majors=("biz",),
       flags=("securities_cert",), tags=("cert", "exam")),
    _c("a_biz_sim_trade", "模拟盘交易", "common", 5, 10,
       "用模拟盘做了半年交易，把每笔买卖的理由记在本子上，最后发现自己跑输了大盘。",
       {"portfolio": 2, "exam": 1, "mind": 2}, majors=("biz",),
       tags=("portfolio", "mind")),
    _c("a_biz_campus_sales", "校园营销实战", "common", 5, 10,
       "接了校园代理的活，在宿舍楼下摆摊卖了两周，算清成本和毛利，也见识了什么叫转化率。",
       {"intern": 2, "network": 2, "mind": 1}, resources={"money": 6},
       majors=("biz",), tags=("work", "money", "intern")),
    _c("a_biz_case_team", "备战案例赛", "common", 5, 10,
       "为案例赛每天练一个 case，从读材料到给出建议只给二十分钟，练到能随手画出框架图。",
       {"portfolio": 3, "mind": 2}, majors=("biz",),
       tags=("contest", "portfolio", "mind")),
    _c("a_biz_bank_visit", "银行开放日", "common", 7, 11,
       "参加银行的校园开放日，问清管培生的轮岗和考核，回来把简历按岗位重排了一遍。",
       {"intern": 2, "network": 2}, majors=("biz",), tags=("work", "network")),
    _c("a_biz_industry_report", "写行业研究", "common", 7, 12,
       "挑了个新能源细分行业，把三家公司五年的财报读完，写出三十页的行业分析报告。",
       {"research": 3, "portfolio": 2, "intern": 1}, majors=("biz",),
       tags=("research", "portfolio")),
    _c("a_biz_financial_model", "搭财务模型", "common", 7, 12,
       "照教程搭了三张表联动的模型，又做了敏感性分析，第一次觉得数字也能讲故事。",
       {"portfolio": 3, "intern": 1, "exam": 1}, majors=("biz",),
       tags=("project", "portfolio")),
    _c("a_biz_cfa_level1", "备考CFA一级", "common", 9, 14,
       "报了 CFA 一级，十个科目每天啃两小时，财报分析和道德部分来回刷了三遍。",
       {"english": 2, "exam": 3, "mind": 1}, resources={"money": -12},
       majors=("biz",), tags=("cert", "exam", "english")),
    _c("a_biz_bigfour_intern", "四大实习", "common", 9, 14,
       "网申、笔试、群面、合伙人面试一路走下来，最后拿到四大审计的寒假实习 offer。",
       {"intern": 4, "network": 1, "mind": 1}, gate={"intern": 6},
       majors=("biz",), tags=("intern", "work"),
       note="群面那天你才发现，会说话和会做事一样重要。"),
    _c("a_biz_ibd_intern", "券商研究所实习", "common", 9, 14,
       "在券商研究所做日常实习，每天整理公告和财务数据，写的第一篇点评被带教改得只剩两句话。",
       {"intern": 4, "research": 1, "mind": 1}, majors=("biz",),
       tags=("intern", "work", "research")),
    _c("a_biz_group_interview", "练群面", "common", 9, 14,
       "和五个同学模拟了四场无领导小组讨论，从抢话到学会做总结，第四次拿了全场第一。",
       {"mind": 3, "network": 2}, majors=("biz",), tags=("work", "mind", "network")),
    _c("a_biz_bookkeeping", "会计实操", "common", 7, 12,
       "在实训平台上从填凭证一路做到出报表，把一整套账做完，终于知道课上的分录落在哪里。",
       {"gpa": 2, "exam": 2, "portfolio": 1}, majors=("biz",),
       tags=("study", "cert")),
    _c("a_biz_client_meeting", "跟客户开会", "common", 9, 14,
       "实习时跟着带教去见客户，负责记会议纪要，会后两小时交出去，带教说这是最加分的活。",
       {"intern": 3, "network": 2, "mind": 1}, majors=("biz",),
       tags=("intern", "work")),
    _c("a_biz_autumn_biz", "秋招投递", "common", 11, 16,
       "把简历按咨询、快消和互联网三条线各改一版，投出去六十多份，笔试做到手熟。",
       {"intern": 3, "mind": 2}, majors=("biz",), tags=("work", "intern")),
    _c("a_biz_case_interview", "练案例面试", "common", 11, 16,
       "找搭档练了三十个 case，把市场估算和利润拆解题型练到能在白板上边画边讲。",
       {"intern": 2, "mind": 2, "english": 1}, majors=("biz",),
       tags=("work", "mind", "english")),
    _c("a_biz_presentation", "上台路演", "common", 9, 14,
       "代表小组上台路演，八分钟讲完被问了六个问题，答到第四个时反而放松下来了。",
       {"portfolio": 2, "leadership": 2, "mind": 1}, majors=("biz",),
       tags=("portfolio", "leadership")),
    _c("a_biz_alumni_referral", "找校友内推", "common", 11, 16,
       "在职业社交平台上给七位校友发了消息，三位回复，其中一位直接把简历转给了 HR。",
       {"network": 3, "intern": 2}, majors=("biz",), tags=("network", "work")),
    _c("a_biz_offer_negotiate", "谈一次薪资", "common", 13, 16,
       "拿到 offer 后试着跟 HR 谈了一次薪资，用另一家的数字做参考，最后涨了一千五。",
       {"intern": 2, "mind": 3}, majors=("biz",), tags=("work", "mind"),
       note="开口谈钱的那一刻，你就不再是学生了。"),
    _c("a_biz_cpa_prep", "备考CPA", "common", 13, 16,
       "毕业前报了 CPA 的会计和审计两科，网课倍速听完，做题做到看见分录就条件反射。",
       {"exam": 3, "gpa": 1, "mind": 1}, majors=("biz",),
       tags=("cert", "exam")),
    _c("a_biz_thesis_case", "案例型毕设", "common", 13, 16,
       "毕设挑了家本地企业做案例研究，访谈五位员工，写了两万字，导师说这些数据很难得。",
       {"research": 3, "portfolio": 2}, majors=("biz",),
       tags=("research", "portfolio")),
    _c("a_biz_office_skills", "练办公软件", "common", 13, 16,
       "把 Word 排版、Excel 函数和 PPT 母版都过了一遍，入职前给自己攒了一套模板库。",
       {"portfolio": 2, "intern": 1, "mind": 1}, majors=("biz",),
       tags=("work", "portfolio")),
    _c("a_biz_offer_pick", "选一家公司", "common", 15, 16,
       "把几个 offer 的城市、薪资和晋升路径列成表，最后选了平台更大但起薪一般的那家。",
       {"mind": 3, "intern": 1}, majors=("biz",), tags=("work", "mind")),
    _c("a_biz_onboard_prep", "入职准备", "common", 15, 16,
       "入职前把租房、体检和银行卡办完，还提前看了两本行业入门书，报到那天不至于手足无措。",
       {"intern": 2, "mind": 2, "body": 1}, majors=("biz",),
       tags=("work", "mind")),
)


# ---------------------------------------------------------------- 机械与能源动力类（30）

MECH_CARDS: tuple[ActionCard, ...] = (
    _c("a_mech_drawing", "机械制图", "common", 1, 4,
       "机械制图课上把三视图画到闭着眼都能想出形状，丁字尺和圆规用了一整个学期。",
       {"gpa": 3, "mind": 1}, majors=("mech",), tags=("study", "gpa")),
    _c("a_mech_theory_mech", "理论力学", "common", 1, 4,
       "理论力学每章例题都自己重推一遍，受力分析画满两个本子，期末考了九十分。",
       {"gpa": 4, "research": 1}, majors=("mech",), tags=("study", "gpa")),
    _c("a_mech_workshop_tour", "进车间看看", "common", 1, 4,
       "跟着学长进了工程训练中心，第一次摸到车床和铣床，手臂被飞出来的铁屑烫了一下。",
       {"body": 1, "research": 1, "mind": 2}, majors=("mech",),
       tags=("lab", "body")),
    _c("a_mech_hand_tools", "学用工具", "common", 2, 5,
       "在创客空间泡了一学期，把锯、锉、钻和攻丝练熟，做出一把歪歪扭扭但能用的锤子。",
       {"body": 2, "portfolio": 2}, majors=("mech",), tags=("project", "body")),
    _c("a_mech_cad", "学CAD", "common", 3, 6,
       "把二维绘图软件练到能盲敲快捷键，一套零件图从开始画到标注完只用一小时。",
       {"portfolio": 3, "gpa": 1}, majors=("mech",), tags=("study", "portfolio")),
    _c("a_mech_solidworks", "三维建模", "common", 3, 6,
       "跟着教程把减速器完整建模并出装配图，干涉检查报了三次错，改到深夜才通过。",
       {"portfolio": 3, "research": 1}, majors=("mech",), tags=("project", "portfolio")),
    _c("a_mech_goldwork", "金工实习", "common", 3, 6,
       "金工实习两周，铸锻焊车铣刨磨轮了一遍，手上磨出水泡，最后交了个自己车的小锤子。",
       {"body": 2, "portfolio": 2, "mind": 1}, majors=("mech",),
       tags=("lab", "body", "portfolio")),
    _c("a_mech_tolerance", "公差与配合", "common", 4, 7,
       "把公差配合和形位公差啃了一遍，课程设计里每个配合都写了理由，被老师圈出来表扬。",
       {"gpa": 3, "research": 1}, majors=("mech",), tags=("study", "gpa")),
    _c("a_mech_material_mech", "材料力学", "common", 5, 8,
       "材料力学把弯曲和扭转的公式全部自己推了一遍，实验报告的误差分析写了三页。",
       {"gpa": 4, "research": 1}, majors=("mech",),
       tags=("study", "gpa", "research")),
    _c("a_mech_3d_print", "玩3D打印", "common", 5, 9,
       "把设计的小机构打印出来装配，公差给大了装不上，改到第四版才转得顺畅。",
       {"portfolio": 3, "research": 1, "mind": 1}, majors=("mech",),
       tags=("project", "portfolio")),
    _c("a_mech_cnc", "数控编程", "common", 5, 9,
       "在数控机床上把一段程序从头调到能跑，对刀对了半小时，第一个零件还是做废了。",
       {"portfolio": 2, "research": 2}, majors=("mech",), tags=("lab", "cert")),
    _c("a_mech_smartcar", "调智能车", "common", 5, 9,
       "为智能车比赛在实验室待到暑假，摄像头阈值调了上百次，车终于能完整跑完一圈。",
       {"portfolio": 3, "mind": 2}, majors=("mech",),
       tags=("contest", "project", "portfolio")),
    _c("a_mech_ansys", "ANSYS仿真", "common", 7, 12,
       "用有限元软件把零件做了静力和模态分析，网格从粗糙加密三遍，结果才收敛。",
       {"research": 3, "portfolio": 2}, majors=("mech",), tags=("research", "project")),
    _c("a_mech_plc", "PLC编程", "common", 7, 12,
       "在实验台上把梯形图写通，控制模拟产线走完流程，接线接错烧掉一个继电器。",
       {"research": 2, "portfolio": 2, "mind": 1}, majors=("mech",),
       tags=("lab", "project")),
    _c("a_mech_hydraulic", "液压气动", "common", 7, 12,
       "把液压回路搭了三遍才不漏油，压力表指针稳住的那刻，你终于看懂了课本上的回路图。",
       {"research": 2, "gpa": 1, "mind": 1}, majors=("mech",),
       tags=("lab", "study")),
    _c("a_mech_factory_visit", "下厂参观", "common", 7, 12,
       "跟着学院去汽车厂参观一天，看冲压线一分钟出十几个件，回来对课本上的工艺有了画面。",
       {"intern": 2, "mind": 2, "network": 1}, majors=("mech",),
       tags=("work", "mind")),
    _c("a_mech_innovate_design", "机械创新设计", "common", 9, 13,
       "为机械创新设计大赛做了一台样机，从选型到装配花了四个月，演示那天机构卡了一次。",
       {"portfolio": 4, "research": 2}, majors=("mech",),
       tags=("contest", "project", "portfolio")),
    _c("a_mech_chem_sim", "化工流程仿真", "common", 9, 13,
       "用流程模拟软件把一个工艺全流程跑通，物料平衡对不上就一项项查，最后误差压到百分之一。",
       {"research": 3, "portfolio": 1, "gpa": 1}, majors=("mech",),
       tags=("research", "project")),
    _c("a_mech_energy_save", "节能减排项目", "common", 9, 13,
       "做了个余热回收的小课题，算清一年能省多少电，报告被推荐去参加节能减排竞赛。",
       {"research": 3, "portfolio": 2}, majors=("mech",),
       tags=("contest", "research", "portfolio")),
    _c("a_mech_production_intern", "生产实习", "common", 9, 14,
       "在制造企业实习一个月，跟着师傅做工艺卡，第一次知道图纸到产品之间还有那么多道手续。",
       {"intern": 4, "research": 1, "mind": 1}, majors=("mech",),
       tags=("intern", "work")),
    _c("a_mech_engineer_cert", "考工程师证", "common", 9, 14,
       "备考见习机械工程师，把机械设计和制造基础两门课重新过了一遍，一次考过。",
       {"exam": 3, "portfolio": 1}, majors=("mech",),
       flags=("mech_engineer_cert",), tags=("cert", "exam")),
    _c("a_mech_design_manual", "翻设计手册", "common", 9, 14,
       "为课程设计把机械设计手册翻了几十页，查标准件和材料牌号，第一次觉得手册比教材有用。",
       {"gpa": 2, "research": 2}, majors=("mech",), tags=("study", "research")),
    _c("a_mech_graduate_course", "考研专业课", "common", 11, 16,
       "机械原理和机械设计两门专业课从头过了一遍，十年真题按考点分类做了两轮。",
       {"exam": 4, "gpa": 1}, majors=("mech",), track="kaoyan",
       tags=("exam", "study")),
    _c("a_mech_patent", "申请专利", "common", 11, 16,
       "把大创里的一个机构改进写成实用新型专利申请，权利要求书改五遍，半年后拿到受理通知。",
       {"portfolio": 3, "research": 2}, majors=("mech",),
       flags=("patent_filed",), tags=("portfolio", "research")),
    _c("a_mech_thesis_prototype", "毕设做样机", "common", 13, 16,
       "毕设做了一台小型样机，零件加工跑了三趟加工厂，装配那天发现轴孔同轴度差了半毫米。",
       {"research": 3, "portfolio": 2}, majors=("mech",),
       tags=("research", "project", "portfolio")),
    _c("a_mech_job_offer", "投制造企业", "common", 13, 16,
       "秋招投了十几家制造企业，面试被问到公差和工艺路线，答得比想象中顺，拿到两个 offer。",
       {"intern": 3, "mind": 2}, majors=("mech",), track="job",
       tags=("work", "intern")),
    _c("a_mech_debug_rig", "帮师兄调台架", "common", 13, 16,
       "在实验室帮师兄调一台试验台，压力上不去就一段段排查，最后发现是个阀门装反了。",
       {"research": 2, "body": 1, "mind": 2}, majors=("mech",),
       tags=("lab", "research", "mind")),
    _c("a_mech_defense", "毕设答辩", "common", 15, 16,
       "毕设答辩讲了十五分钟，评委问到加工精度和成本，你把零件实物拿出来，气氛一下松了。",
       {"research": 3, "portfolio": 1, "mind": 1}, majors=("mech",),
       tags=("research", "portfolio")),
    _c("a_mech_onboard", "入职准备", "common", 15, 16,
       "入职前把制图和三维软件又练了一遍，还提前查了公司主要产品的结构和型号。",
       {"intern": 2, "mind": 2}, majors=("mech",), tags=("work", "mind")),
    _c("a_mech_skill_cert", "考数控中级", "common", 9, 14,
       "考了数控中级工证书，实操考件做废一个，第二次把进给量调稳才通过。",
       {"portfolio": 2, "exam": 1, "body": 1}, majors=("mech",),
       flags=("cnc_cert",), tags=("cert", "exam", "body")),
)


# ---------------------------------------------------------------- 土木与水利类（30）

CIVIL_CARDS: tuple[ActionCard, ...] = (
    _c("a_civil_drawing", "识图入门", "common", 1, 4,
       "把一套住宅施工图从头到尾看了一遍，对着平法图集查钢筋标注，看得眼睛发酸。",
       {"gpa": 3, "research": 1}, majors=("civil",), tags=("study", "gpa")),
    _c("a_civil_theory_mech", "理论力学打底", "common", 1, 4,
       "理论力学把静定结构的内力分析练到看图就能出结果，课后题做满两本练习册。",
       {"gpa": 4, "mind": 1}, majors=("civil",), tags=("study", "gpa")),
    _c("a_civil_material_lab", "打混凝土试块", "common", 1, 4,
       "在材料实验室做混凝土试块，养护二十八天后压出强度值，误差比预想大，报告里认真分析了原因。",
       {"research": 2, "gpa": 1, "body": 1}, majors=("civil",),
       tags=("lab", "study")),
    _c("a_civil_first_site", "第一次下工地", "common", 2, 5,
       "跟着老师去工地参观，戴着安全帽在脚手架下面走，第一次知道图纸上的线在现实里有多粗。",
       {"body": 1, "intern": 2, "mind": 1}, majors=("civil",),
       tags=("work", "body")),
    _c("a_civil_survey", "测量实习", "common", 3, 6,
       "测量实习两周，扛着全站仪在校园里跑了几十个控制点，闭合差超限就重测一遍。",
       {"body": 2, "research": 2, "portfolio": 1}, majors=("civil",),
       tags=("lab", "body", "research")),
    _c("a_civil_structure_mech", "结构力学", "common", 3, 7,
       "结构力学的力法和位移法各刷了一百道题，超静定结构终于不再靠猜。",
       {"gpa": 4, "research": 1}, majors=("civil",), tags=("study", "gpa")),
    _c("a_civil_cad_drawing", "画施工图", "common", 3, 7,
       "用制图软件画了一套小建筑的平立剖，标注改到第五版才勉强符合规范。",
       {"portfolio": 3, "gpa": 1}, majors=("civil",), tags=("project", "portfolio")),
    _c("a_civil_bim_first", "BIM入门", "common", 4, 8,
       "学 BIM 建模软件，把一栋小楼从轴网建到屋顶，第一次用三维看清了管线怎么打架。",
       {"portfolio": 3, "research": 1}, majors=("civil",), tags=("project", "portfolio")),
    _c("a_civil_concrete", "混凝土结构", "common", 5, 8,
       "混凝土结构设计原理啃了两遍，配筋计算写满一整本，课程设计拿了优秀。",
       {"gpa": 4, "portfolio": 1}, majors=("civil",), tags=("study", "gpa")),
    _c("a_civil_structure_contest", "结构设计竞赛", "common", 5, 10,
       "为结构设计竞赛用竹皮做模型，加载前刮掉多余的胶，扛到第三级才断，拿了校赛二等奖。",
       {"portfolio": 4, "mind": 2}, majors=("civil",),
       tags=("contest", "project", "portfolio")),
    _c("a_civil_soil_mech", "土力学试验", "common", 5, 9,
       "直剪和三轴试验各做了一遍，把数据整理成曲线，终于明白什么叫有效应力。",
       {"research": 3, "gpa": 1}, majors=("civil",), tags=("lab", "research")),
    _c("a_civil_geology", "地质实习", "common", 5, 10,
       "地质实习一周，背着地质锤和罗盘在山上跑，敲了一背包石头回来，学会了看产状。",
       {"body": 2, "research": 2, "mind": 1}, majors=("civil",),
       tags=("lab", "body", "research")),
    _c("a_civil_bim_deep", "BIM碰撞检查", "common", 7, 12,
       "把机电管线和土建模型合到一起做碰撞检查，找出四十多处冲突，还写了份优化建议。",
       {"portfolio": 3, "research": 2, "intern": 1}, majors=("civil",),
       tags=("project", "portfolio")),
    _c("a_civil_construction_org", "施工组织设计", "common", 7, 12,
       "做了份施工组织设计，进度计划横道图画了三版，塔吊布置被老师挑出两处不合理。",
       {"research": 3, "portfolio": 1}, majors=("civil",), tags=("project", "research")),
    _c("a_civil_site_intern", "工地实习", "common", 7, 12,
       "在工地实习一个月，跟着施工员放线、验筋、看打灰，晒黑一圈也看懂了大半本图纸。",
       {"intern": 4, "body": 1, "mind": 1}, majors=("civil",),
       tags=("intern", "work", "body")),
    _c("a_civil_cost", "学造价算量", "common", 7, 12,
       "跟着软件算了一栋楼的工程量清单，钢筋算量对不上就一条条查，最后误差控制在百分之二。",
       {"intern": 2, "research": 2, "portfolio": 1}, majors=("civil",),
       tags=("work", "research")),
    _c("a_civil_hydraulic", "水利方向", "common", 9, 13,
       "选了水工建筑物方向，把重力坝的稳定和应力算了一遍，课程设计画了六张图。",
       {"gpa": 3, "research": 2}, majors=("civil",), tags=("study", "research")),
    _c("a_civil_harbor", "港航方向", "common", 9, 13,
       "跟着老师做港口规划的课程设计，把泊位数量和吞吐量算了三天，第一次接触海岸动力。",
       {"research": 3, "gpa": 1}, majors=("civil",), tags=("research", "study")),
    _c("a_civil_ocean_eng", "海洋工程导论", "common", 9, 14,
       "上了海洋工程导论选修课，做了个导管架平台的受力分析，发现海上荷载比陆地复杂得多。",
       {"research": 3, "portfolio": 1}, majors=("civil",), tags=("research", "study")),
    _c("a_civil_second_builder", "考二建", "common", 9, 14,
       "备考二级建造师，法规和管理两门刷了一千多道题，实务案例写了满满一本。",
       {"exam": 4, "portfolio": 1}, majors=("civil",),
       flags=("second_builder",), tags=("cert", "exam"),
       note="书上那些条款，工地上真的会一条条对着查。"),
    _c("a_civil_graduate_course", "考研专业课", "common", 11, 16,
       "结构力学和材料力学按考研大纲重新过一遍，真题做了十年，错题按题型归了类。",
       {"exam": 4, "gpa": 1}, majors=("civil",), track="kaoyan",
       tags=("exam", "study")),
    _c("a_civil_design_institute", "设计院实习", "common", 11, 16,
       "在设计院实习，跟着工程师改了三版楼梯详图，被指出标注不规范的地方有十几处。",
       {"intern": 4, "research": 1, "mind": 1}, majors=("civil",),
       tags=("intern", "work")),
    _c("a_civil_structure_software", "结构计算软件", "common", 9, 14,
       "用结构计算软件建模算了一栋框架，把参数从默认值改成规范值，配筋结果差了不少。",
       {"research": 3, "portfolio": 1}, majors=("civil",), tags=("project", "research")),
    _c("a_civil_thesis_design", "毕设做设计", "common", 13, 16,
       "毕设是一栋六层办公楼的全套结构设计，计算书一百多页，图纸改了七版才定稿。",
       {"research": 3, "portfolio": 2}, majors=("civil",),
       tags=("research", "project", "portfolio")),
    _c("a_civil_job_offer", "投施工单位", "common", 13, 16,
       "秋招面试施工单位，被问到能不能接受外派，你说了能，两周后拿到了 offer。",
       {"intern": 3, "mind": 2}, majors=("civil",), track="job",
       tags=("work", "intern")),
    _c("a_civil_real_project", "跟一个真项目", "common", 13, 16,
       "跟着导师做了一个加固改造项目，去现场看了三次，第一次知道规范之外还有现场经验。",
       {"research": 3, "intern": 2}, majors=("civil",),
       tags=("research", "intern", "work")),
    _c("a_civil_defense", "毕设答辩", "common", 15, 16,
       "毕设答辩被问了三个问题，其中一个关于抗震构造，你翻到图纸第三张指给评委看。",
       {"research": 3, "portfolio": 1, "mind": 1}, majors=("civil",),
       tags=("research", "portfolio")),
    _c("a_civil_onboard", "入职准备", "common", 15, 16,
       "入职前把平法图集和常用规范又翻了一遍，还提前联系同批入职的同事一起看房。",
       {"intern": 2, "mind": 2}, majors=("civil",), tags=("work", "mind")),
    _c("a_civil_arch_software", "学建筑表现", "common", 13, 16,
       "把建筑建模和渲染软件各学一个月，能独立出一套效果图，班里的展示材料都来找你。",
       {"portfolio": 3, "mind": 1}, majors=("civil",), tags=("project", "portfolio")),
    _c("a_civil_safety_cert", "考安全员证", "common", 11, 16,
       "考了建筑安全员 C 证，把安全规范和事故案例过了一遍，考试那天提前一小时交了卷。",
       {"exam": 2, "portfolio": 1, "body": 1}, majors=("civil",),
       flags=("safety_cert",), tags=("cert", "exam")),
)


# ---------------------------------------------------------------- 数理基础科学类（30）

SCI_CARDS: tuple[ActionCard, ...] = (
    _c("a_sci_math_analysis", "数分高代", "common", 1, 4,
       "数学分析和高等代数每天各刷十道题，把定理证明自己重写一遍，笔记本写到第三本。",
       {"gpa": 4, "mind": 1}, majors=("sci",), tags=("study", "gpa")),
    _c("a_sci_physics_lab", "大学物理实验", "common", 1, 4,
       "物理实验每次课前把原理抄一遍，报告里的误差分析写了半页，实验分排到班里前几。",
       {"research": 2, "gpa": 2}, majors=("sci",), tags=("lab", "study")),
    _c("a_sci_chem_lab", "基础化学实验", "common", 1, 4,
       "化学实验课从称量练到滴定，终点判断练到半滴不差，实验记录写得像一本账。",
       {"research": 2, "gpa": 1, "body": 1}, majors=("sci",),
       tags=("lab", "study")),
    _c("a_sci_seminar_first", "进讨论班", "common", 2, 5,
       "被学长拉进讨论班，第一次听别人讲论文，全程只懂了开头，但把不懂的词全记了下来。",
       {"research": 2, "mind": 2, "network": 1}, majors=("sci",),
       tags=("research", "mind")),
    _c("a_sci_reading_paper", "读第一篇论文", "common", 3, 6,
       "啃一篇英文综述，一个下午只看了三页，把不认识的术语做成一张表，一周后读完了。",
       {"research": 3, "english": 1}, majors=("sci",), tags=("research", "english")),
    _c("a_sci_math_contest", "数学竞赛备赛", "common", 3, 7,
       "为数学竞赛把高数竞赛题刷了两本，极限和中值定理的证明套路总结成一页纸。",
       {"gpa": 3, "portfolio": 2}, majors=("sci",),
       tags=("contest", "study", "gpa")),
    _c("a_sci_programming", "学编程处理数据", "common", 3, 7,
       "为处理实验数据学了编程，把一学期数据画成图，助教问你愿不愿意帮课题组做分析。",
       {"research": 2, "portfolio": 2, "network": 1}, majors=("sci",),
       tags=("project", "research")),
    _c("a_sci_lab_helper", "进实验室帮忙", "common", 4, 8,
       "在实验室帮师兄跑数据，从洗仪器开始干，两个月后终于被允许独立做一个小组实验。",
       {"research": 3, "network": 1, "mind": 1}, majors=("sci",),
       tags=("lab", "research")),
    _c("a_sci_real_analysis", "实变与泛函", "common", 5, 9,
       "实变函数和泛函分析两门硬课一起上，定理证明抄了三遍，期末靠默写证明过了关。",
       {"gpa": 4, "mind": 2}, majors=("sci",), tags=("study", "gpa", "mind")),
    _c("a_sci_stat_model", "统计建模", "common", 5, 10,
       "用统计软件把一份问卷数据做了回归和聚类，模型跑通那刻，第一次觉得公式有用。",
       {"research": 3, "portfolio": 1}, majors=("sci",), tags=("research", "project")),
    _c("a_sci_chem_innovate", "自拟化学课题", "common", 5, 10,
       "在化学实验室做自拟课题，合成路线试了七次才拿到目标产物，产率只有百分之十二。",
       {"research": 4, "mind": 2}, majors=("sci",), tags=("lab", "research")),
    _c("a_sci_bio_skill", "生物实验技能", "common", 5, 10,
       "把移液、跑胶、细胞培养这些基本功练熟，第一次独立做 PCR 时手都不敢抖。",
       {"research": 3, "body": 1}, majors=("sci",), tags=("lab", "research")),
    _c("a_sci_yau_contest", "丘赛备赛", "common", 7, 12,
       "为丘成桐大学生数学竞赛挑了分析与方程方向，往年题做了一遍，笔试那天只做出两道。",
       {"gpa": 3, "portfolio": 2, "mind": 1}, majors=("sci",),
       tags=("contest", "study", "portfolio")),
    _c("a_sci_physics_model", "物理自选实验", "common", 7, 12,
       "为物理实验竞赛做了个自选实验，从搭光路到处理数据全自己来，误差来源写了整整一页。",
       {"research": 3, "portfolio": 2}, majors=("sci",),
       tags=("contest", "research", "portfolio")),
    _c("a_sci_data_clean", "数据清洗实战", "common", 7, 12,
       "接了个帮课题组清洗数据的活，几千行里挑出三百多条异常，写脚本批量处理完。",
       {"research": 3, "portfolio": 1, "intern": 1}, majors=("sci",),
       tags=("research", "project")),
    _c("a_sci_seminar_talk", "讨论班讲一次", "common", 7, 12,
       "在讨论班上讲了篇论文，准备两周，被问到第三步的推导时卡住，回去补了三天。",
       {"research": 3, "mind": 2, "english": 1}, majors=("sci",),
       tags=("research", "mind")),
    _c("a_sci_research_project", "独立小课题", "common", 9, 13,
       "导师给了个小课题让你自己跑，从查文献到出结果花了四个月，中间推翻过一次假设。",
       {"research": 4, "mind": 2}, majors=("sci",), flags=("lab_member",),
       gate={"research": 8}, track="research", tags=("lab", "research")),
    _c("a_sci_paper_write", "写第一篇论文", "common", 9, 14,
       "把课题结果写成论文，图表改了十几遍，导师说讨论部分写得比结果部分好。",
       {"research": 4, "portfolio": 2, "english": 1}, majors=("sci",),
       gate={"research": 10}, track="research", tags=("research", "portfolio")),
    _c("a_sci_ta", "当实验助教", "common", 9, 14,
       "给大一当实验课助教，讲了两轮操作规范，被学生问住一次，回去把讲义重看了一遍。",
       {"gpa": 2, "leadership": 2, "network": 1}, majors=("sci",),
       tags=("study", "leadership")),
    _c("a_sci_math_model", "打数学建模", "common", 7, 12,
       "组队打数学建模，三天只睡八个小时，最后交上去的论文里有两张图是凌晨四点画的。",
       {"research": 3, "portfolio": 2, "mind": 1}, majors=("sci",),
       tags=("contest", "research", "portfolio")),
    _c("a_sci_camp_apply", "夏令营套磁", "common", 11, 15,
       "给六所高校的老师发了邮件，附上成绩单和课题小结，三位回复说欢迎来夏令营。",
       {"network": 3, "research": 2}, majors=("sci",), gate={"gpa": 13},
       track="baoyan", tags=("network", "research", "portfolio")),
    _c("a_sci_camp_interview", "夏令营面试", "common", 11, 15,
       "夏令营面试被要求现场推导一个公式，写完手心全是汗，老师说思路是对的。",
       {"mind": 3, "research": 2, "english": 1}, majors=("sci",),
       track="baoyan", tags=("research", "mind")),
    _c("a_sci_graduate_course", "考研专业课", "common", 11, 16,
       "数学分析和高代按考研大纲重刷一遍，真题做了十五年，常考证明题整理成一本。",
       {"exam": 4, "gpa": 1}, majors=("sci",), track="kaoyan",
       tags=("exam", "study")),
    _c("a_sci_thesis", "毕设做课题", "common", 13, 16,
       "毕设接着课题往下做，补了三组实验，论文写了三万字，附录里的原始数据有二十页。",
       {"research": 4, "portfolio": 2}, majors=("sci",),
       tags=("research", "portfolio")),
    _c("a_sci_abroad_apply", "申请海外项目", "common", 13, 16,
       "准备海外博士项目材料，推荐信找了三位老师，个人陈述里写的是做课题时的一次失败。",
       {"english": 3, "portfolio": 2, "mind": 1}, majors=("sci",),
       gate={"english": 12}, track="abroad", tags=("english", "portfolio")),
    _c("a_sci_phd_choice", "决定读不读博", "common", 13, 16,
       "把读博和工作的两条路各列了一张表，找五位师兄聊过之后，在纸上圈了读博。",
       {"mind": 3, "research": 1}, majors=("sci",),
       flags=("direct_phd_intent",), track="research", tags=("mind", "research")),
    _c("a_sci_defense", "毕设答辩", "common", 15, 16,
       "毕设答辩被问了四个问题，其中一个质疑你的对照组，你把两组数据并排画出来当场解释。",
       {"research": 3, "portfolio": 1, "mind": 1}, majors=("sci",),
       tags=("research", "portfolio")),
    _c("a_sci_grad_life", "提前进组", "common", 15, 16,
       "保研后提前进组，暑假就跟着开组会，师兄说这一步让你研一能省下半年。",
       {"research": 3, "network": 1, "mind": 1}, majors=("sci",),
       track="research", tags=("lab", "research")),
    _c("a_sci_teaching_cert", "考教师资格证", "common", 13, 16,
       "顺手考了教师资格证，笔试三门一次过，面试试讲被评委说板书太乱。",
       {"exam": 2, "leadership": 2}, majors=("sci",), flags=("teacher_cert",),
       tags=("cert", "exam")),
    _c("a_sci_peer_review", "帮师兄改稿", "common", 13, 16,
       "帮师兄的论文改了一轮语言和图表，第一次站在审稿人的角度读别人的工作。",
       {"research": 3, "english": 2}, majors=("sci",), tags=("research", "english")),
)


# ---------------------------------------------------------------- 人文社科类（28）

HUM_CARDS: tuple[ActionCard, ...] = (
    _c("a_hum_intensive_reading", "精读外刊", "common", 1, 4,
       "每周精读一篇外刊，生词、句式和背景都记进本子，一学期攒了四十页笔记。",
       {"english": 4, "mind": 1}, majors=("hum",), tags=("english", "study")),
    _c("a_hum_writing_habit", "每天写五百字", "common", 1, 4,
       "每天写五百字，什么都写，一个月后翻回去看，发现自己的句子变短了也变清楚了。",
       {"portfolio": 3, "mind": 2}, majors=("hum",), tags=("portfolio", "mind")),
    _c("a_hum_classics_read", "读经典", "common", 1, 4,
       "把一本古代文学经典从头读到尾，做了详细批注，读书报告被老师当范文念了一段。",
       {"gpa": 3, "mind": 1}, majors=("hum",), tags=("study", "gpa")),
    _c("a_hum_putonghua_drill", "练普通话", "common", 1, 5,
       "对着普通话测试的六十篇朗读作品练了两个月，前后鼻音终于能分清。",
       {"exam": 2, "mind": 2}, hobby=("reading", C.HOBBY_XP_PER_ACTION), majors=("hum",),
       tags=("cert", "mind")),
    _c("a_hum_debate_team", "进辩论队", "common", 3, 7,
       "过了辩论队选拔，第一次正式比赛前查了三十页资料，场上被抓住漏洞，下来哭了半小时。",
       {"mind": 3, "network": 2, "portfolio": 1}, majors=("hum",),
       tags=("social", "mind", "portfolio")),
    _c("a_hum_speech_contest", "演讲比赛", "common", 3, 7,
       "报名演讲比赛，稿子改到第七版，上台前手心出汗，讲完的掌声比预想的要热烈。",
       {"mind": 3, "portfolio": 2}, majors=("hum",),
       tags=("contest", "portfolio", "mind")),
    _c("a_hum_second_language", "学第二外语", "common", 3, 7,
       "选了日语选修课，从五十音图学到能看懂简单新闻标题，每周背一百个单词。",
       {"english": 2, "gpa": 2, "mind": 1}, majors=("hum",), tags=("study", "english")),
    _c("a_hum_putonghua_exam", "考普通话等级", "common", 3, 8,
       "考了普通话水平测试，命题说话环节卡了一次壳，最后拿了二级甲等。",
       {"exam": 2, "portfolio": 1, "mind": 1}, majors=("hum",),
       flags=("putonghua_2a",), tags=("cert", "exam")),
    _c("a_hum_tem4", "专四备考", "common", 5, 8,
       "专四备考三个月，十年真题的听力反复精听，听写从错八个练到只错两个。",
       {"english": 4, "mind": 2}, majors=("hum",), flags=("tem4",),
       tags=("english", "exam")),
    _c("a_hum_moot_court", "模拟法庭", "common", 5, 10,
       "进了模拟法庭队伍，写了二十页代理词，庭上被连着质证三轮，老师最后点了点头。",
       {"portfolio": 3, "exam": 2, "english": 1}, majors=("hum",),
       tags=("contest", "portfolio", "exam")),
    _c("a_hum_ad_creative", "做广告创意", "common", 5, 10,
       "为大广赛做了三套创意方案，被否掉两套，剩下那套熬三个通宵做成了视频。",
       {"portfolio": 4, "mind": 2}, majors=("hum",),
       tags=("contest", "portfolio", "mind")),
    _c("a_hum_literature_paper", "写文学评论", "common", 5, 10,
       "为一篇小说写了八千字评论，把能找到的研究都读了一遍，导师批注写满两页。",
       {"research": 3, "portfolio": 2}, majors=("hum",),
       tags=("research", "portfolio")),
    _c("a_hum_tem8", "专八冲刺", "common", 7, 12,
       "专八前两个月每天一套真题，改错和翻译各刷两本，考试那天提前二十分钟做完。",
       {"english": 4, "exam": 1}, majors=("hum",), gate={"english": 10},
       flags=("tem8",), tags=("english", "exam")),
    _c("a_hum_teacher_skill", "练教学技能", "common", 7, 12,
       "为师范生技能竞赛练了二十次片段教学，板书练到能徒手画直线，教案写了十五份。",
       {"leadership": 2, "portfolio": 2, "mind": 1}, majors=("hum",),
       tags=("contest", "portfolio", "leadership")),
    _c("a_hum_translation", "接笔译外包", "common", 7, 12,
       "接了一份两万字的翻译外包，查了上百个术语，交稿后对方说下次还找你。",
       {"english": 3, "portfolio": 2, "mind": 1}, resources={"money": 8},
       majors=("hum",), tags=("english", "work", "money")),
    _c("a_hum_philosophy", "啃哲学导论", "common", 7, 12,
       "啃完一本哲学导论，边读边写问题清单，读完发现自己以前很多想法都站不住。",
       {"mind": 3, "gpa": 1}, majors=("hum",), tags=("study", "mind")),
    _c("a_hum_law_exam", "法考备考", "common", 9, 14,
       "开始准备法律职业资格考试，八门部门法一轮轮过，客观题考完手都在抖。",
       {"exam": 4, "gpa": 1, "mind": 1}, majors=("hum",), gate={"exam": 8},
       tags=("cert", "exam")),
    _c("a_hum_media_intern", "媒体实习", "common", 9, 14,
       "在本地媒体实习，跟着记者跑了六条线，独立写的稿子第一次被署上名字。",
       {"intern": 3, "portfolio": 2}, majors=("hum",),
       tags=("intern", "work", "portfolio")),
    _c("a_hum_english_speech", "英语演讲赛", "common", 9, 14,
       "为外研社演讲赛写了三版稿子，即兴环节抽到一道关于人工智能的题，硬着头皮讲满三分钟。",
       {"english": 4, "mind": 2}, majors=("hum",),
       tags=("contest", "english", "mind")),
    _c("a_hum_research_method", "学研究方法", "common", 9, 14,
       "补了社会科学研究方法的课，把问卷设计和访谈提纲各写一份，导师说可以拿去做课题。",
       {"research": 3, "portfolio": 1}, majors=("hum",), tags=("research", "study")),
    _c("a_hum_graduate_course", "考研专业课", "common", 11, 16,
       "把文学史和文学理论按考研大纲重新梳理，做了两份思维导图，真题背了三轮。",
       {"exam": 4, "portfolio": 1}, majors=("hum",), track="kaoyan",
       tags=("exam", "study")),
    _c("a_hum_camp_apply", "夏令营投递", "common", 11, 15,
       "投了五所学校的夏令营，个人陈述里写的是自己做过的两次田野调查，收到三个入营通知。",
       {"portfolio": 3, "network": 2}, majors=("hum",), gate={"gpa": 13},
       track="baoyan", tags=("portfolio", "network")),
    _c("a_hum_publish_essay", "发表一篇小文章", "common", 11, 16,
       "把一篇课程论文改了两个月投出去，半年后收到用稿通知，稿费两百块，你截图发了朋友圈。",
       {"research": 3, "portfolio": 2, "mind": 1}, majors=("hum",),
       flags=("essay_published",), tags=("research", "portfolio")),
    _c("a_hum_thesis", "写毕业论文", "common", 13, 16,
       "毕业论文写了四万字，引注核对了三遍，答辩前一周还在补一节田野材料。",
       {"research": 4, "portfolio": 2}, majors=("hum",), tags=("research", "portfolio")),
    _c("a_hum_job_offer", "投媒体与教育", "common", 13, 16,
       "秋招投了媒体、教育和出版三类岗位，面试时被要求现场写一篇评论，四十分钟交稿。",
       {"intern": 3, "mind": 2, "portfolio": 1}, majors=("hum",), track="job",
       tags=("work", "intern")),
    _c("a_hum_civil_servant", "考公备考", "common", 13, 16,
       "开始备考公务员，行测每天一套，申论每周两篇，把近三年的政策文件读了一遍。",
       {"exam": 4, "leadership": 1}, majors=("hum",), track="gov",
       tags=("exam", "party")),
    _c("a_hum_defense", "毕设答辩", "common", 15, 16,
       "答辩时评委问你的材料和结论之间有没有断层，你如实说了局限，老师反而说这态度难得。",
       {"research": 3, "mind": 2}, majors=("hum",), tags=("research", "mind")),
    _c("a_hum_teacher_cert", "考教师资格证", "common", 15, 16,
       "考了教师资格证，笔试一次过，面试试讲被评委说语速太快，第二次压着节奏讲完。",
       {"exam": 2, "leadership": 2, "mind": 1}, majors=("hum",),
       flags=("teacher_cert",), tags=("cert", "exam")),
)


# ---------------------------------------------------------------- 海洋与水产类（26）

OCEAN_CARDS: tuple[ActionCard, ...] = (
    _c("a_ocean_intro", "海洋科学导论", "common", 1, 4,
       "把海洋科学导论读完，第一次搞懂洋流、潮汐和温盐环流，还在本子上画了张全球洋流图。",
       {"gpa": 3, "research": 1}, majors=("ocean",), tags=("study", "gpa")),
    _c("a_ocean_seashore", "去海边采样", "common", 1, 4,
       "跟着师兄去海边采水样，第一次穿救生衣上小艇，浪一大就吐了，样品还是抱回了实验室。",
       {"body": 2, "research": 2}, majors=("ocean",),
       tags=("lab", "body", "research")),
    _c("a_ocean_chem", "海水化学分析", "common", 1, 4,
       "把海水化学的分析方法过了一遍，滴定测盐度练到误差控制在千分之二以内。",
       {"research": 2, "gpa": 2}, majors=("ocean",), tags=("lab", "study")),
    _c("a_ocean_fish_id", "认鱼虾贝藻", "common", 2, 5,
       "在标本室泡了一学期，把常见鱼虾贝藻认了个遍，同学开始管你叫活体图鉴。",
       {"research": 2, "gpa": 1, "body": 1}, majors=("ocean",),
       tags=("lab", "study")),
    _c("a_ocean_survey_skill", "学海洋调查", "common", 3, 7,
       "学采水器和采泥器怎么用，跟着出海一次，把一整天站位的数据按规范记全了。",
       {"research": 3, "body": 2}, majors=("ocean",),
       tags=("lab", "research", "body")),
    _c("a_ocean_water_test", "水质检测", "common", 3, 7,
       "按国标方法练测氨氮、总磷和溶解氧，从采样到记录全程掐表，误差一次比一次小。",
       {"research": 3, "portfolio": 1}, majors=("ocean",),
       tags=("contest", "lab", "research")),
    _c("a_ocean_knowledge", "海洋知识竞赛", "common", 3, 7,
       "为海洋知识竞赛背了两个月题库，从海洋生物到海洋权益，决赛抢答时手速慢了半拍。",
       {"portfolio": 3, "mind": 1}, majors=("ocean",),
       tags=("contest", "portfolio", "mind")),
    _c("a_ocean_aqua", "水产养殖实践", "common", 4, 8,
       "在养殖基地待了两周，喂料、测水温、看溶氧，第一次知道一池虾会因缺氧一夜之间全没。",
       {"body": 2, "research": 2, "mind": 1}, majors=("ocean",),
       tags=("lab", "body", "research")),
    _c("a_ocean_red_tide", "赤潮藻培养", "common", 5, 10,
       "跟着课题组做赤潮藻培养，显微镜下数了一下午细胞，数据记满三页表格。",
       {"research": 4, "mind": 1}, majors=("ocean",), tags=("lab", "research")),
    _c("a_ocean_boat_intern", "船基实习", "common", 5, 10,
       "出海实习一周，值夜班时守着采水器看星星，回来把航次报告整理成四十页。",
       {"body": 3, "research": 3, "mind": 1}, majors=("ocean",),
       tags=("lab", "research", "body")),
    _c("a_ocean_diving", "考潜水证", "common", 5, 10,
       "用一个暑假考到开放水域潜水证，水下十米做完耳压平衡那刻，觉得之前的紧张都值了。",
       {"body": 3, "portfolio": 2, "mind": 1}, resources={"money": -12},
       majors=("ocean",), flags=("diving_cert",), tags=("cert", "body", "sport")),
    _c("a_ocean_policy", "学海洋政策", "common", 5, 10,
       "把海洋生态文明和海洋权益相关的政策文件读了一遍，写了篇关于伏季休渔的分析。",
       {"exam": 2, "research": 2, "mind": 1}, majors=("ocean",), track="gov",
       tags=("study", "exam", "research")),
    _c("a_ocean_model", "跑海洋数值模型", "common", 7, 12,
       "跑了一遍区域海洋数值模型，参数调了两周，模拟潮位和实测对得上，你在机房笑出声。",
       {"research": 4, "portfolio": 1}, majors=("ocean",), tags=("research", "project")),
    _c("a_ocean_aqua_design", "养殖方案设计", "common", 7, 12,
       "为渔菁英挑战赛做了套养殖方案，从苗种密度算到投饵量，答辩被问病害防控时卡了壳。",
       {"research": 3, "portfolio": 2}, majors=("ocean",),
       tags=("contest", "research", "portfolio")),
    _c("a_ocean_restore", "生态修复方案", "common", 7, 12,
       "参加环境生态科技创新大赛，做了个河道生态修复方案，成本和日处理量算了三遍。",
       {"research": 3, "portfolio": 2}, majors=("ocean",),
       tags=("contest", "research", "portfolio")),
    _c("a_ocean_lab_join", "进课题组", "common", 7, 12,
       "正式进了海洋生态课题组，每周开组会汇报进展，第一次有了自己的工位和实验台。",
       {"research": 3, "network": 1, "mind": 1}, majors=("ocean",),
       flags=("lab_member",), gate={"research": 6}, track="research",
       tags=("lab", "research")),
    _c("a_ocean_cruise", "参加科考航次", "common", 9, 14,
       "跟着科考船出海二十天，晕船晕了三天才适应，负责的温盐深数据一条没落下。",
       {"research": 4, "body": 3, "mind": 1}, majors=("ocean",),
       gate={"body": 8}, track="research", tags=("lab", "research", "body")),
    _c("a_ocean_polar", "极地科考宣讲", "common", 9, 14,
       "听了极地科考的宣讲会，把报名条件和体检要求记下来，回来开始每天跑步练体能。",
       {"body": 3, "research": 1, "mind": 2}, majors=("ocean",),
       flags=("polar_intent",), track="research", tags=("research", "body", "mind")),
    _c("a_ocean_paper", "写海洋生态论文", "common", 9, 14,
       "把航次数据整理成一篇论文，图重画了六遍，导师说方法部分写得比讨论扎实。",
       {"research": 4, "portfolio": 2}, majors=("ocean",), gate={"research": 10},
       track="research", tags=("research", "portfolio")),
    _c("a_ocean_marine_art", "海洋文创", "common", 9, 14,
       "为海洋文化创意设计大赛做了一组海报，把本地渔港的故事画进去，拿了省里的奖。",
       {"portfolio": 4, "mind": 1}, majors=("ocean",),
       tags=("contest", "portfolio", "mind")),
    _c("a_ocean_camp", "夏令营申请", "common", 11, 15,
       "把三个航次经历和一篇论文写进个人陈述，投了四所海洋院所，收到两个夏令营通知。",
       {"portfolio": 3, "network": 2}, majors=("ocean",), gate={"gpa": 12},
       track="baoyan", tags=("portfolio", "network")),
    _c("a_ocean_graduate_course", "考研专业课", "common", 11, 16,
       "海洋科学导论和海洋化学按考研大纲过一遍，真题做了十年，名词解释抄成一本。",
       {"exam": 4, "research": 1}, majors=("ocean",), track="kaoyan",
       tags=("exam", "study")),
    _c("a_ocean_aqua_cert", "考水产技术员", "common", 11, 16,
       "考了水产技术员职业资格，把病害防治和饲料配方的题刷了两遍，一次通过。",
       {"exam": 3, "portfolio": 1}, majors=("ocean",), flags=("aqua_cert",),
       tags=("cert", "exam")),
    _c("a_ocean_thesis", "毕设出海取样", "common", 13, 16,
       "毕设的数据是自己出海采的，在海上待了半个月，回来分析数据又花了两个月。",
       {"research": 4, "portfolio": 2, "body": 2}, majors=("ocean",),
       tags=("research", "lab", "body")),
    _c("a_ocean_job_offer", "投海洋与环保岗", "common", 13, 16,
       "秋招投了海洋院所、环保企业和水产公司三类岗位，最后拿到一份水质监测的 offer。",
       {"intern": 3, "mind": 2}, majors=("ocean",), track="job",
       tags=("work", "intern")),
    _c("a_ocean_defense", "毕设答辩", "common", 15, 16,
       "答辩时你把采样照片贴进 PPT，评委说看得出现场功夫下得够，问的全是数据细节。",
       {"research": 3, "portfolio": 1, "mind": 1}, majors=("ocean",),
       tags=("research", "portfolio")),
)


# ---------------------------------------------------------------- 医学与生命科学类（26）

MED_CARDS: tuple[ActionCard, ...] = (
    _c("a_med_anatomy", "解剖课", "common", 1, 4,
       "解剖课第一次上台，握着器械的手不太稳，一学期后能闭着眼说出主要神经的走向。",
       {"gpa": 4, "body": 1, "mind": 1}, majors=("med",),
       tags=("study", "gpa", "body")),
    _c("a_med_physiology", "生理学", "common", 1, 4,
       "生理学把每一章的机制图自己画一遍，循环和呼吸那两章画了整整一本。",
       {"gpa": 4, "research": 1}, majors=("med",), tags=("study", "gpa")),
    _c("a_med_histology", "组织学切片", "common", 1, 4,
       "组织学切片看了一百多张，把每个器官的典型结构画在卡片上，考前翻了三遍。",
       {"gpa": 3, "mind": 1}, majors=("med",), tags=("study", "gpa")),
    _c("a_med_terms", "背医学名词", "common", 2, 5,
       "把解剖和生理的英文名词整理了六百个，每天早晚各背一遍，读文献时终于不用全靠猜。",
       {"english": 3, "gpa": 1}, majors=("med",), tags=("english", "study")),
    _c("a_med_biochem", "生物化学", "common", 3, 7,
       "生物化学的代谢通路画了十几张图，把糖脂蛋白代谢串成一张总图贴在床头。",
       {"gpa": 4, "research": 1}, majors=("med",), tags=("study", "gpa")),
    _c("a_med_pathology", "病理学", "common", 3, 7,
       "病理切片和标本各看了一遍，把常见病变的特征做成对比表，期末考了班里前五。",
       {"gpa": 4, "research": 1}, majors=("med",), tags=("study", "gpa")),
    _c("a_med_first_aid", "学急救", "common", 3, 7,
       "考了急救证，心肺复苏练到按压深度和频率都成了肌肉记忆，回宿舍还教了室友一遍。",
       {"body": 2, "portfolio": 1, "mind": 2}, majors=("med",),
       flags=("first_aid_cert",), tags=("cert", "body", "mind")),
    _c("a_med_skill_center", "技能中心练手", "common", 3, 8,
       "在临床技能中心练无菌操作和穿刺，护士长站在旁边盯着，一项操作练了三十遍。",
       {"body": 2, "research": 1, "mind": 2}, majors=("med",),
       tags=("lab", "body", "mind")),
    _c("a_med_clinical_skill", "临床技能竞赛", "common", 5, 10,
       "为临床技能竞赛在模拟人上练站式考核，问诊查体穿刺一套掐着表走，超时两次。",
       {"portfolio": 4, "body": 1, "mind": 2}, majors=("med",),
       tags=("contest", "portfolio", "body")),
    _c("a_med_pharm", "药理学", "common", 5, 9,
       "药理学把每个药的机制、适应症和不良反应做成表格，背到看见药名就想起禁忌。",
       {"gpa": 4, "exam": 1}, majors=("med",), tags=("study", "gpa")),
    _c("a_med_imaging", "学影像判读", "common", 5, 10,
       "跟着老师看了一百多张片子，从胸片开始练，第一次独立认出气胸时有点激动。",
       {"research": 3, "gpa": 1}, majors=("med",), tags=("lab", "research")),
    _c("a_med_nursing_skill", "练护理操作", "common", 5, 10,
       "练了无菌、输液和导尿，每一项都有评分表，同学互相扎针，手背青了两块。",
       {"body": 2, "portfolio": 2, "mind": 1}, majors=("med",),
       tags=("lab", "body", "portfolio")),
    _c("a_med_clerkship", "医院见习", "common", 7, 12,
       "在医院见习两周，跟着查房换药写病历，第一次被病人叫大夫时愣了一下。",
       {"intern": 4, "mind": 2}, majors=("med",), tags=("intern", "work", "mind")),
    _c("a_med_rotation", "临床轮转", "common", 7, 12,
       "在内科和外科各轮一个月，值了一个夜班，凌晨三点的急诊让你彻底清醒了。",
       {"intern": 4, "body": 2, "mind": 1}, majors=("med",),
       tags=("intern", "work", "body")),
    _c("a_med_medlit", "读医学文献", "common", 7, 12,
       "把专科方向的英文文献读了二十篇，做了份证据等级表，查房被主治问到时答上了。",
       {"research": 3, "english": 2}, majors=("med",), tags=("research", "english")),
    _c("a_med_research_train", "科研训练", "common", 7, 12,
       "进实验室做基础医学课题，养细胞跑蛋白印迹，第一次拿到条带时拍照发到了群里。",
       {"research": 4, "mind": 1}, majors=("med",), flags=("lab_member",),
       gate={"research": 6}, track="research", tags=("lab", "research")),
    _c("a_med_licence", "执业医师备考", "common", 9, 14,
       "开始准备执业医师考试，内外妇儿一轮轮过，题库刷到第一万题时已经麻木了。",
       {"exam": 4, "gpa": 2, "mind": 1}, majors=("med",), gate={"gpa": 10},
       tags=("cert", "exam")),
    _c("a_med_case_report", "写病例报告", "common", 9, 14,
       "跟着老师整理了一份罕见病例报告，随访资料翻了两年的病历，最后写了五千字。",
       {"research": 3, "portfolio": 2}, majors=("med",), track="research",
       tags=("research", "portfolio")),
    _c("a_med_basicmed", "基础医学论坛", "common", 9, 14,
       "为基础医学创新论坛做了个实验设计，海报改了三版，答辩时被问到对照组怎么设。",
       {"research": 3, "portfolio": 2}, majors=("med",),
       tags=("contest", "research", "portfolio")),
    _c("a_med_public_health", "社区筛查", "common", 9, 14,
       "跟着疾控做了一次社区筛查，量血压、录数据、做健康宣教，一天下来嗓子哑了。",
       {"intern": 2, "network": 2, "body": 1}, majors=("med",),
       tags=("volunteer", "intern", "body")),
    _c("a_med_camp", "夏令营申请", "common", 11, 15,
       "把科研经历和成绩排名写进个人陈述，投了四所医院的夏令营，收到两个入营通知。",
       {"portfolio": 3, "network": 2}, majors=("med",), gate={"gpa": 12},
       track="baoyan", tags=("portfolio", "network")),
    _c("a_med_graduate_course", "考研西综", "common", 11, 16,
       "西综按考研大纲过了两遍，生理生化病理内外科各做十套模拟，错题抄满两本。",
       {"exam": 4, "gpa": 1, "mind": 1}, majors=("med",), track="kaoyan",
       tags=("exam", "study")),
    _c("a_med_paper", "投稿医学论文", "common", 11, 16,
       "把课题结果整理成稿投出去，审稿意见回来了六条，补实验补了两个月。",
       {"research": 4, "portfolio": 2, "mind": 1}, majors=("med",),
       gate={"research": 10}, flags=("paper_submitted",), track="research",
       tags=("research", "portfolio")),
    _c("a_med_thesis", "毕设做临床课题", "common", 13, 16,
       "毕设做了个回顾性临床研究，调了三百多份病历，统计跑了十几遍才控住混杂因素。",
       {"research": 4, "portfolio": 2}, majors=("med",),
       tags=("research", "portfolio")),
    _c("a_med_job_offer", "规培与就业", "common", 13, 16,
       "在规培和直接就业之间权衡了很久，最后签了家乡三甲医院的规培并留院协议。",
       {"intern": 3, "mind": 2}, majors=("med",), track="job",
       tags=("work", "mind")),
    _c("a_med_defense", "毕设答辩", "common", 15, 16,
       "答辩时评委问你的统计方法选得对不对，你把敏感性分析的表翻出来，对方点了点头。",
       {"research": 3, "portfolio": 1, "mind": 1}, majors=("med",),
       tags=("research", "portfolio")),
)


MAJOR_CARDS: tuple[ActionCard, ...] = (
    CS_CARDS + BIZ_CARDS + MECH_CARDS + CIVIL_CARDS
    + SCI_CARDS + HUM_CARDS + OCEAN_CARDS + MED_CARDS
)


# ================================================================ 竞赛阶梯卡（按 contests.STAGE_CARDS 生成）

# 阶梯 → 品质（国赛/国际赛才有 epic 的分量）
_TIER_RARITY: dict[str, str] = {
    "school": "common",
    "prov": "rare",
    "national": "epic",
    "intl": "epic",
}


def _contest_stage_id(contest_id: str, tier: str) -> str:
    """取这一阶的卡片 id：优先用 contests 里排好的 STAGE_CARDS。"""
    table = K.STAGE_CARDS.get(contest_id) or {}
    card_id = table.get(tier)
    if card_id:
        return card_id
    return K.stage_card_id(contest_id, tier)


# 每一阶"你具体干了什么"。刻意不在正文里重复竞赛名 —— 卡名里已经有了，
# 而竞赛名长短不一（最长的十二个字），塞进正文会把 60 字上限撑爆。
_STAGE_TEXT: dict[str, str] = {
    "school": "在教务系统里报了名，组好队占好机房，连着两周晚上都在改方案，先把校赛这一关稳稳打下来。",
    "prov": "校赛出线后带着材料去外地比了三天，答辩前一晚在酒店会议室排练了六遍，回来时奖状卷在背包里。",
    "national": "为国赛请了半个月假，白天做晚上改，决赛现场看到别人的作品才知道自己差在哪，但名次比想象中好。",
    "intl": "带着成果去打国际赛，全程英文答辩，被评委追问到第三轮时手心全是汗，最后站上领奖台拍了合影。",
}

# 竞赛卡的复盘旁白（按阶梯给一句，不按竞赛逐条写）
_STAGE_NOTE: dict[str, str] = {
    "school": "第一次把课堂上的东西拿去跟人比。",
    "prov": "省赛的这张奖状，是简历上能写的第一行。",
    "national": "站上国赛的场地，你才知道自己和顶尖差多少。",
    "intl": "能走到国际赛场这一步的人，本来就不多。",
}


def _build_contest_cards() -> tuple[ActionCard, ...]:
    """每个竞赛的每一阶生成一张行动卡。

    数量与 ``contests.STAGE_CARDS`` 里的总阶数完全一致。
    竞赛卡自身不带属性收益 —— 收益由 ``effects.py`` 按
    ``CONTEST_TIER_EFFECT`` × 竞赛 strengths 结算。
    """
    cards: list[ActionCard] = []
    seen: set[str] = set()
    for contest in K.CONTEST_LIST:
        for tier in contest.tiers:
            if tier not in C.CONTEST_TIERS:
                continue
            card_id = _contest_stage_id(contest.id, tier)
            if card_id in seen:
                continue
            seen.add(card_id)
            cards.append(
                ActionCard(
                    id=card_id,
                    name=f"{contest.name}・{C.CONTEST_TIER_NAMES[tier]}",
                    text=_STAGE_TEXT[tier],
                    rarity=_TIER_RARITY[tier],
                    sem_lo=C.CONTEST_TIER_EARLIEST[tier],
                    sem_hi=C.TOTAL_SEMESTERS,
                    effects={},
                    resources={},
                    flags=(),
                    hobby=None,
                    majors=tuple(contest.majors),
                    is_flex=contest.is_flex,
                    tags=("contest", "portfolio"),
                    track="",
                    attribute_gate={},
                    start_affinity=(),
                    contest_id=contest.id,
                    contest_tier=tier,
                    note=_STAGE_NOTE[tier],
                )
            )
    return tuple(cards)


CONTEST_CARDS: tuple[ActionCard, ...] = _build_contest_cards()


# ================================================================ 汇总与查询

ALL_CARDS: tuple[ActionCard, ...] = GENERAL_CARDS + MAJOR_CARDS + CONTEST_CARDS

CARDS: dict[str, ActionCard] = {card.id: card for card in ALL_CARDS}


def get(card_id: str) -> ActionCard:
    """按 id 取卡；不存在直接 KeyError，方便早发现拼写错误。"""
    return CARDS[card_id]


# 竞赛卡标了 is_flex 时，哪些专业看得见由 contests.for_major 说了算 ——
# 邻接表只维护在 contests.py 一份，这里不重复定义，避免两边跑偏。
_FLEX_CACHE: dict[str, tuple[str, ...]] = {}


def _visible_majors(card: ActionCard) -> tuple[str, ...]:
    """这张卡实际能被哪些专业看见（竞赛卡展开 is_flex）。"""
    if not card.majors:
        return M.all_ids()
    if not card.is_flex or not card.contest_id:
        return card.majors
    cached = _FLEX_CACHE.get(card.contest_id)
    if cached is None:
        cached = tuple(
            major_id
            for major_id in M.all_ids()
            if any(c.id == card.contest_id for c in K.for_major(major_id))
        )
        _FLEX_CACHE[card.contest_id] = cached
    return cached or card.majors


def for_major(major_id: str) -> list[ActionCard]:
    """某个专业能看见的全部卡片（通用卡 + 本专业专属卡）。"""
    return [card for card in ALL_CARDS if major_id in _visible_majors(card)]


def cards_for_semester(sem: int, major_id: str) -> list[ActionCard]:
    """某个专业在某学期能用的卡片。时间窗是闭区间 [sem_lo, sem_hi]。"""
    return [
        card
        for card in ALL_CARDS
        if card.sem_lo <= sem <= card.sem_hi and major_id in _visible_majors(card)
    ]


def card_is_contest(card: ActionCard) -> bool:
    """是不是竞赛阶梯卡。"""
    return bool(card.contest_id and card.contest_tier)


def contest_cards() -> list[ActionCard]:
    """全部竞赛阶梯卡。"""
    return [card for card in ALL_CARDS if card_is_contest(card)]


def rest_cards() -> list[ActionCard]:
    """保底休息卡：safe 品质且带 rest / sport tag。"""
    return [
        card
        for card in ALL_CARDS
        if card.rarity == "safe" and any(tag in C.REST_TAGS for tag in card.tags)
    ]


def major_cards(major_id: str) -> list[ActionCard]:
    """某个专业真正专属的卡（不含通用卡与竞赛卡）。"""
    return [
        card
        for card in MAJOR_CARDS
        if major_id in card.majors and not card.is_flex and not card.contest_id
    ]


def semester_coverage(major_id: str) -> dict[int, int]:
    """某个专业每个学期各有多少张专属可用卡（自检用）。"""
    return {
        sem: len(
            [
                card
                for card in major_cards(major_id)
                if card.sem_lo <= sem <= card.sem_hi
            ]
        )
        for sem in range(1, C.TOTAL_SEMESTERS + 1)
    }
